linuxdeepin/dde-shell

- example/applet-example-data/exampleapplet.cpp
- example/applet-example-data/exampleapplet.h
- example/panel-example/examplepanel.cpp
- frame/applet.cpp
- frame/applet.h
- frame/appletitem.cpp
- frame/panel.cpp
- frame/private/applet_p.h
- frame/private/panel_p.h
- frame/qmlengine.cpp
Add rootObject property to export AppletItem.
> feat: support to access AppletItem for Applet

- example/panel-example/package/main.qml
Applet.appletItem[0] access object which has not ready in runtime.
> fix: example crashed

- example/panel-example/package/main.qml
- frame/layershell/dlayershellwindow.cpp
- frame/layershell/qwaylandlayershellsurface.cpp
- frame/layershell/x11dlayershellemulation.cpp
- frame/layershell/x11dlayershellemulation.h
1. waylandSurafce not update after layershell perproty changed, because not commit changed, so now manually call waylandSurface()->commit()
2. x11emulation not make window keep in center, can not get window size in qml before when init, but now connectted widthChanged and heightChanged.
3. unable to anchor three sides, beacause wayland when setSize QSize::isEmpty get a unexpected result when width or height is 0, x11 not modify window size reason as above 2.
log: fix above bugs
> fix: layershell wrap bugs

- frame/CMakeLists.txt
Change 'PUBLIC' to 'PRIVATE' for PkgConfig::XCB in cmake
Log: Change 'PUBLIC' to 'PRIVATE' for PkgConfig::XCB
> chore: Change 'PUBLIC' to 'PRIVATE' for PkgConfig::XCB

- example/containment-example/examplecontainment.cpp
- example/containment-example/package/main.qml
- frame/applet.cpp
- frame/containment.cpp
- frame/panel.cpp
- frame/pluginloader.cpp
- frame/pluginmetadata.cpp
- frame/private/applet_p.h
- frame/private/panel_p.h
- shell/main.cpp
we should release rootObject when removeApplet.
`load` doesn't be called in createApplet, it should be called
manually like `init` function.
> fix: release rootObject when delete Applet

- panels/dock/package/main.qml
- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/package/TaskManager.qml
Fix transparent mouse event delivery. Use exclusive grab to make sure mouse event is just handle by one handler.
Log: fix transparent mouse event
> fix: transparent mouse event

- panels/dock/taskmanager/appitem.cpp
when docked status changed need to recheck checkAppItemNeedDeleteAndDelete
log: as title
> fix: undock appitem but it not removed

- panels/dock/CMakeLists.txt
- panels/dock/MenuHelper.qml
- panels/dock/package/main.qml
- panels/dock/taskmanager/package/AppItem.qml
Cause native popup is a xdg_popup, and layer shell surface is not managed by xdg-shell. We manually manage the focus of menu by introducing a MenuHelper Singleton.
Log: fix menu not closed when popup second one
> fix: menu not closed when popup second one

- frame/qml/PanelPopup.qml
it exists padding for Popup.
removing background for Popup temporarily.
> fix: PanelPopup's size is wrong

- frame/layershell/qwaylandlayershellsurface.cpp
- frame/layershell/qwaylandlayershellsurface_p.h
When changing anchors, size might be invalid for a short period. This might lead to a protocol error. Cache anchors and size, commit them together.
Log: fix protocol error when changing anchors
> fix: protocol error when changing anchors

- panels/dock/package/main.qml
Adding property binding to update SortFilterModel.
> fix: SortFilterModel can't update when item's property changed

- panels/dock/package/main.qml
use Binding instead of Qt.binding for loading plugins early
log: as title
> refact: use Binding instead of Qt.binding

- debian/dde-shell.install
- debian/libdde-shell.install
- panels/dock/dockplugin/plugin/CMakeLists.txt
Do not install libdde-dockplugin-interface.so to any package. Just use its soname link in dde-shell.
Log: adjust package install files
> chore: adjust package install files

- panels/dock/showdesktop/showdesktop.cpp
- panels/dock/showdesktop/showdesktop.h
make show-desktop plugin not load on treeland
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/6909
> fix: show-desktop shown on treeland

- panels/dock/DockCompositor.qml
- panels/dock/dockplugin/loader/main.cpp
- panels/dock/dockplugin/loader/widgetplugin.cpp
- panels/dock/dockplugin/plugin/dockplugin.h
- panels/dock/dockplugin/plugin/dockpluginmanager.cpp
- panels/dock/dockplugin/plugin/dockpluginmanager_p.h
- panels/dock/dockplugin/plugin/dockpluginsurface.cpp
- panels/dock/dockplugin/protocol/dock-plugin-manager-v1.xml
- panels/dock/dockpluginmanagerextension.cpp
- panels/dock/dockpluginmanagerextension_p.h
- panels/dock/package/main.qml
- panels/dock/tray/package/tray.qml
1. wayland compositor send event, need to specify the client to receive the message default client is null which will make assert invalid.
2. forward surface destory signal, and remove saved surface in DockCompositor
log: fix dock plugin theme not follow dock
issue: https://github.com/linuxdeepin/developer-center/issues/6879
> fix: plugin theme not followed dock

- panels/dock/dockplugin/loader/widgetplugin.cpp
network use updateDockInfo ti update it's icon
log: update plugin tray icon when call updateDockInfo
> fix: dock network plugin not update

- panels/dock/dockpanel.cpp
- panels/dock/dockpanel.h
- panels/dock/package/main.qml
make unimplement menu enabled when debugMode
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/6943
> chore: add debugMode and disable some menu

- panels/dock/dockpanel.cpp
since NDEBUG not existed, use QT_DEBUG instead
log: remove NDEBUG and use QT_DEBUG
> fix: debugMode get wrong

- panels/dock/CMakeLists.txt
Log: only use include interface
> chore: don't link dde-shell-frame to dock-plugin

- panels/dock/taskmanager/desktopfileamparser.cpp
> fix: never call am to identfy when no am desktopparser constructed

- frame/qml/PanelPopup.qml
- frame/qml/PanelPopupWindow.qml
- frame/qml/PanelToolTip.qml
Using transientParent's position as PopupPanelWindow's leftTop position.
> fix: wrong position for PopupPanel in x11

- CMakeLists.txt
- applets/CMakeLists.txt
- applets/dde-am/CMakeLists.txt
- applets/dde-am/amapplet.cpp
- applets/dde-am/amapplet.h
- applets/dde-am/package/metadata.json
We connect app removed signal of AM to reset appsLaunchedTimes
int `dde-am` set when app uninstalled,
> feat: add AM applet to reset appsLaunchedTimes

- panels/dock/taskmanager/desktopfileamparser.cpp
- panels/dock/taskmanager/desktopfileamparser.h
Launching app by dde-am tools instead of calling dbus directly.
> refact: launching app by dde-am tool

- panels/dock/tray/plugins/system-monitor/gui/monitor_plugin.cpp
log: should not do resize as there is setting setDevicePixelRatio
> fix: system-monitor set error ratio for icon in QuickShow

- panels/dock/tray/frame/dockapplet.cpp
- panels/dock/tray/frame/dockapplet.h
Register 'WidgetProxy' in plugin load.
Log: fix dock tray not show
Influence: tray area display
> fix: fix dock tray not show

- panels/dock/taskmanager/x11preview.cpp
Don't multiply by device pixel ratio.
> fix: preview window radius calculation error

- panels/dock/package/main.qml
Add conditional binding from itemIconSizeBase to dockMaxItemSize.
> fix: lose binding when not resize

- panels/dock/tray/frame/util/imageutil.cpp
- panels/dock/tray/plugins/shutdown/shutdownplugin.cpp
log: should not init by scaled size also setDevicePixelRatio
issue: https://github.com/linuxdeepin/developer-center/issues/7859
> fix: error ratio when set AA_UseHighDpiPixmaps

- debian/rules
- panels/dock/tray/networkmanager-qt/src/CMakeLists.txt
- panels/dock/tray/plugins/dde-network-core/dock-network-plugin/CMakeLists.txt
Remove NMQT_STATIC, it's used in test.
Add ENABLE_DEEPIN_NMQT in rules.
issue: https://github.com/linuxdeepin/developer-center/issues/7880
> fix: can't connect wifi for tray

- panels/dock/tray/frame/dockapplet.cpp
- panels/dock/tray/frame/dockapplet.h
- panels/dock/tray/frame/quickproxywidget.cpp
- panels/dock/tray/frame/window/components/datetimedisplayer.cpp
- panels/dock/tray/frame/window/docktraywindow.cpp
- panels/dock/tray/frame/window/tray/tray_gridview.cpp
- panels/dock/tray/plugins/dde-network-core/dock-network-plugin/quickpanel.cpp
- panels/dock/tray/plugins/pluginmanager/quicksettingitem.cpp
as title
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7862
> fix: fix quick tray icon not show in vertical center

- panels/dock/tray/frame/package/tray.qml
Add 12 pixels to the width or height of the tray area according to the design
Log: fix no distance between dateTime and showDesktop
Influence: distance between dateTime and showDesktop
> fix: fix no distance between dateTime and showDesktop

- panels/dock/taskmanager/desktopfileamparser.cpp
Dock did not carry the action parameter when launching the application by clicking on the menu
Issue: https://github.com/linuxdeepin/developer-center/issues/7891
> fix: unable to launch  terminal with quake-mode by dock menu

- panels/dock/taskmanager/x11preview.cpp
The close button of the preview widget has no hover state
Log: fix The close button of the preview window has no hover state
Influence: preview widget's close button hover state
> fix: the close button of the preview widget has no hover state

- panels/dock/tray/plugins/power/powerplugin.cpp
The battery plugin tooltips does not display the remaining charging time and the remaining usage time when not charged is unrealistic.
Log: battery plugin tooltips show remaining time info
Issue: https://github.com/linuxdeepin/developer-center/issues/8006
Influence: battery plugin tooltips show remaining time info
> fix: battery plugin tooltips show remaining time info

- panels/dock/launcherItem/package/launcheritem.qml
Replacing left align with center align.
> fix: launchpad's left align

- shell/main.cpp
Don't use inactive color group in dde-shell.
Log: don't use inactive color group in dde-shell
> feat: don't use inactive color group

- panels/dock/launcherItem/package/launcheritem.qml
- panels/dock/package/main.qml
- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/package/TaskManager.qml
1. 9:14 (iconSize/dockHeight)
2. 1:4 the distance between app : dock height; get width/height≈0.8
3. indicator margins = 2
Log: modify the distance between app icons
Issue: https://github.com/linuxdeepin/developer-center/issues/7969
Influence: the distance between app icons and indicator margins
> fix: modify the distance between app icons and indicator margins

- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/x11preview.cpp
paint event get new preview content frequently make kwin a high cpu make a timer show preview 500ms later
log: as title
> fix: x11 preview show without content

- panels/dock/dconfig/org.deepin.ds.dock.json
- panels/dock/dockdbusproxy.cpp
- panels/dock/dockdbusproxy.h
- panels/dock/docksettings.cpp
- panels/dock/docksettings.h
save the visibility of a plugin item by dconfig tool
Issue: https://github.com/linuxdeepin/developer-center/issues/7959
> fix: don't save the visibility

- panels/dock/taskmanager/package/AppItem.qml
Disable align when centered in app item.
Log: fix app icon not centered
Issue: https://github.com/linuxdeepin/developer-center/issues/7941
Depends: https://github.com/linuxdeepin/dtkdeclarative/pull/322
> fix: app icon not centered

- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/package/AppItemPalette.qml
As title, adjust indicator palette according to design, temporarily use highlight color for active item.
Log: adjust indicator palette
Issue: https://github.com/linuxdeepin/developer-center/issues/7945
> fix: adjust indicator palette

- panels/dock/clipboarditem/clipboarditem.cpp
- panels/dock/clipboarditem/clipboarditem.h
- panels/dock/searchitem/searchitem.cpp
log: 插件 dci 图标以前景色填充，使用默认 palette 暗亮色可能会有问题
https://desktopspec.org/unstable/%E5%9B%BE%E6%A0%87%E6%96%87%E4%BB%B6%E8%A7%84%E8%8C%83.html
> fix: error palette when get pixmap form dci

- panels/dock/tray/frame/util/dockpopupwindow.cpp
- panels/dock/tray/frame/util/dockpopupwindow.h
- panels/dock/tray/frame/window/quickpluginwindow.cpp
tips radius set to 4 by design.
Log:
> chore: update tray tips radius

- panels/dock/package/main.qml
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8075
TODO: popup and tooltip window colorSelector get wrong color need fix at Dtk
> fix: not set themeType to DWindow

- panels/dock/taskmanager/desktopfileamparser.cpp
return a default icon when desktopfile parser get a empty icon
log: as title
> fix: no icon when desktopfile no icon defined

- panels/dock/tray/translate_generation.sh
Support rpm base distributions.
Log: The 64bit libraries is in the /usr/lib64 in Fedora, openSUSE and other rpm base distributions. Please don't hardcode it.
> fix: don't hardcode the path of lrelease

- panels/dock/dockpanel.cpp
don't emit FrontendWindowRectChanged signal
Issue: https://github.com/linuxdeepin/developer-center/issues/8026
> fix: don't emit FrontendWindowRectChanged signal

- debian/changelog
bump version 0.0.10
log: as title
> chore: bump version 0.0.10

- panels/dock/taskmanager/package/AppItem.qml
Don't use half pixel alignment. Force status indicator to align with icon.
Log: fix icon blurry
Depends: https://github.com/linuxdeepin/dtkdeclarative/pull/327
> fix: icon blurry

- panels/dock/workspaceitem/CMakeLists.txt
- panels/dock/workspaceitem/desktops.cpp
- panels/dock/workspaceitem/desktops.h
- panels/dock/workspaceitem/package/workspaceitem.qml
- panels/dock/workspaceitem/workspacemodel.cpp
- panels/dock/workspaceitem/workspacemodel.h
- panels/dock/workspaceitem/xworkspaceworker.cpp
- panels/dock/workspaceitem/xworkspaceworker.h
Implement workspace functionality using the KWin interface.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8023
> fix: After logging out, the workspace icons are not displayed

- debian/changelog
- panels/dock/taskmanager/package/TaskManager.qml
bump version 0.0.12
log: as title
> chore: bump version 0.0.12

- panels/dock/tray/frame/window/tray/widgets/expandiconwidget.cpp
The mapToGlobal function returns incorrect coordinates, which should be fixed by checking the underMouse status of the collapse button.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8175
> fix: Clicking the collapse button does not collapse the tray view.

- panels/dock/package/main.qml
- panels/dock/searchitem/package/searchitem.qml
- panels/dock/taskmanager/package/AppItem.qml
It's crashed in DPlatformWindowHelper's eventFilter, it should use
DNoTitlebarWindowHelper when dxcb is loaded.
Delay to create Menu avoid to applied an DPlatformWindowHelper in dxcb
when WM is not ready.
Issue: https://github.com/linuxdeepin/developer-center/issues/8243
> fix: crashed when open dock's menu

- panels/dock/CMakeLists.txt
- panels/dock/dconfig/org.deepin.ds.dock.power.json
- panels/dock/tray/plugins/power/powerplugin.cpp
Corrected the way of fetching DConfig configurations so that it will get the same config as dde-control-center
Issue: https://github.com/linuxdeepin/developer-center/issues/8144
Log: "showtimetofull" option didn't work
> fix: "showtimetofull" option didn't work

- panels/dock/multitaskview/multitaskview.cpp
- panels/dock/multitaskview/multitaskview.h
- panels/dock/multitaskview/package/multitaskview.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/8224
Log: Hide multitask button when composition is disabled
> feat: Hide multitask button when composition is disabled

- panels/dock/tray/frame/window/quickpluginwindow.cpp
tipWidget is release by plugin instead of tray frame in previous code.
We reset tipWidget's parent when leaveEvent instead of deconstruction.
> fix: crashed by tipWidget when exit

- debian/changelog
- panels/dock/taskmanager/package/TaskManager.qml
- panels/dock/workspaceitem/package/workspaceitem.qml
bump version 0.0.14
log: as title
> chore: bump version 0.0.14

- frame/qml/PanelToolTip.qml
- panels/dock/launcherItem/package/launcheritem.qml
- panels/dock/multitaskview/package/multitaskview.qml
- panels/dock/taskmanager/package/AppItem.qml
> feat: Move tooltipShowTimer to Item

- panels/dock/package/main.qml
previent hover event from dragMouseArea to app mouseArea
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8287
> fix: tooltip shown when drag dock

- frame/qml/PanelPopupWindow.qml
lower window's size causes window's shadow incorrect,
and removing shadowOffset.
Issue: https://github.com/linuxdeepin/developer-center/issues/8071
> fix: window display abnormality for PanelToolTip

- panels/dock/taskmanager/x11preview.cpp
1.solve the problem that the preview window displays abnormally when the one of app pages is closed 2.The preview window displays abnormally when there is no window effects.
Log: Solve the problem of small icons in the quick panel under high zoom
issue: https://github.com/linuxdeepin/developer-center/issues/8311
Influence: preview display
> fix: fix preview widget display abnormally

- panels/dock/tray/frame/dockapplet.cpp
- panels/dock/tray/frame/dockapplet.h
- panels/dock/tray/frame/package/tray.qml
- panels/dock/tray/frame/window/docktraywindow.cpp
- panels/dock/tray/frame/window/docktraywindow.h
- panels/dock/tray/frame/window/tray/widgets/expandiconwidget.cpp
When the dock size is changed, the tray will collapse.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8315
> fix: When dragging the tray application, tray expansion box is hidden.

- panels/dock/tray/plugins/system-monitor/gui/monitor_plugin.cpp
modify launch system-monitor by AM dbus
Log: modify launch system-monitor by AM dbus
issue: https://github.com/linuxdeepin/developer-center/issues/8319
Influence: dock can display system-monitor app icon
> fix: modify launch system-monitor by AM dbus

- panels/dock/DockPalette.qml
- panels/dock/showdesktop/package/showdesktop.qml
fix show-desktop line color error by new design.
Log: fix show-desktop line color error
issue: https://github.com/linuxdeepin/developer-center/issues/8284
Influence: show-desktop line
> fix: fix show-desktop line color error

- panels/dock/tray/plugins/power/powerplugin.cpp
- panels/dock/tray/plugins/power/powerstatuswidget.cpp
Fixed the issue where the power icon displays incorrectly
Log: fix the power icon displays incorrectly
issue: https://github.com/linuxdeepin/developer-center/issues/8347
Influence: power icon display
> fix: fix the power icon displays incorrectly

- panels/dock/taskmanager/package/AppItem.qml
rebind icon scale
Log: fix the size of app icon when resizing dock size by dcc
issue: https://github.com/linuxdeepin/developer-center/issues/8401
Influence: icon size
> fix: fix the size of app icon when resizing dock size by dcc

- panels/dock/clipboarditem/package/clipboarditem.qml
- panels/dock/searchitem/package/searchitem.qml
it's a bug for dtk, we use IconOnly to avoid the bug.
Issue: https://github.com/linuxdeepin/developer-center/issues/8409
> fix: button's icon is not clear

- panels/dock/tray/frame/window/docktraywindow.cpp
- panels/dock/tray/frame/window/quickpluginwindow.cpp
仅支持托盘内部图标拖拽时显示+标志
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8208
> fix: drag mark error

- panels/dock/tray/frame/window/tray/widgets/xembedtrayitemwidget.cpp
企业微信、向日葵这类应用在高倍缩放情况下，在任务栏上显示的图标太大
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8372
> fix: some icon too large

- frame/qml/PanelPopup.qml
- frame/qml/PanelToolTip.qml
TODO: why Panel.toolTipWindow is undefined.
> chore: remove warning

- panels/dock/tray/frame/util/dockpopupwindow.cpp
- panels/dock/tray/frame/window/components/datetimedisplayer.cpp
- panels/dock/tray/frame/window/systempluginwindow.cpp
点击弹窗上面的内容，弹窗总会自动隐藏，原因是坐标计算错误，导致误认为是点击了窗口外部区域从而隐藏
log: as title
> fix: popup window always hide

- panels/dock/tray/plugins/bluetooth/bluetoothitem.cpp
- panels/dock/tray/plugins/bluetooth/componments/bluetoothadapteritem.cpp
- panels/dock/tray/plugins/bluetooth/componments/bluetoothapplet.cpp
- panels/dock/tray/plugins/bluetooth/componments/bluetoothapplet.h
fix: bluetooth popup has no blur effect and wrong position of separator line 
fix bluetooth popup has no blur effect and wrong position of separator line 
Log: fix bluetooth popup has no blur effect and wrong position of separator line 
Issue: https://github.com/linuxdeepin/developer-center/issues/8494
Influence: bluetooth popup has blur effect
> fix: bluetooth popup has no blur effect

- panels/dock/tray/frame/window/tray/tray_gridview.cpp
- panels/dock/tray/frame/window/tray/tray_model.cpp
- panels/dock/tray/frame/window/tray/tray_model.h
dragging an icon from the tray to dock, but show error app in dock tray area.
Log: fix dragging tray icon to dock, but show error app in dock tray area
issue: https://github.com/linuxdeepin/developer-center/issues/8480
Influence: drag tray icon to dock
> fix: dragging tray icon to dock, but show error app in dock tray area

- panels/dock/tray/frame/window/quickpluginwindow.cpp
use menu popup
Log: tray plugin mouse right click menu causing dock to crash
Issue: https://github.com/linuxdeepin/developer-center/issues/8506
Influence: tray plugin mouse right click menu
> fix: tray plugin mouse right click menu causing dock to crash

- cmake/DDEShellPackageMacros.cmake
remove set_source_files_properties OUTPUT_LOCATION
Log:
> fix: qt 6.7 cannot build

- panels/dock/dockpanel.cpp
- panels/dock/dockpanel.h
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8502
> fix: dock not shown with launchpad

- debian/changelog
- panels/dock/tray/plugins/uos-ai/CMakeLists.txt
- panels/dock/tray/plugins/uos-ai/dbus/org.desktopspec.ObjectManager1.xml
- panels/dock/tray/plugins/uos-ai/dbus/types/am.h
- panels/dock/tray/plugins/uos-ai/uosaiplugin.cpp
> feat: remove uos-ai plugin when uos ai uninstalled

- panels/dock/tray/frame/window/quickpluginwindow.cpp
1.double screen and set extended mode
2.adjust dock height size
3.logout computer and then click the tray plugin right-click menu when the dock comes out
Log: fix tray plugin mouse right click cause dock crash
Issue: https://github.com/linuxdeepin/developer-center/issues/8506
Influence: tray plugin menu display
> fix: tray plugin mouse right click cause dock crash

- debian/changelog
- panels/dock/tray/frame/window/tray/tray_delegate.h
- panels/dock/tray/frame/window/tray/widgets/snitrayitemwidget.cpp
> fix: app tray icon size not same as plugin

- panels/dock/taskmanager/x11preview.cpp
fix x11 preview title length too small
Log: fix x11 preview title length too small
Influence: x11 preview title display
> fix: x11 preview title length too small

- panels/dock/taskmanager/abstractwindowmonitor.h
- panels/dock/taskmanager/waylandwindowmonitor.cpp
- panels/dock/taskmanager/waylandwindowmonitor.h
- panels/dock/taskmanager/x11windowmonitor.cpp
- panels/dock/taskmanager/x11windowmonitor.h
When Qt program use QT_WAYLAND_RECONNECT environment, Qt will reconnect wayland compositor. We need refresh all data.
> feat: support reconnect wayland compositor

- panels/dock/tray/frame/util/dockpopupwindow.cpp
- panels/dock/tray/frame/util/dockpopupwindow.h
- panels/dock/tray/plugins/pluginmanager/pluginchildpage.cpp
- panels/dock/tray/plugins/pluginmanager/pluginchildpage.h
- panels/dock/tray/plugins/sound/sounddeviceswidget.cpp
1. childPage content widget need reset parent to null when hide
2. remove tooltip Widget parent
log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/8604
> fix: coredump app exit after open quick panel childPage

- panels/dock/taskmanager/x11preview.cpp
Solve the problem of blurry images in the preview widget.
Log: x11 preview content is blurry
Influence: x11 preview content
> fix: x11 preview content is blurry

- panels/dock/taskmanager/package/AppItem.qml
When the dock triggers overflow, the tooltip overlaps with the dock.
Log: fix tooltip overlaps with dock
issue: https://github.com/linuxdeepin/developer-center/issues/8171
Influence: tooltip display
> fix: tooltip overlaps with dock

- panels/dock/taskmanager/x11preview.cpp
use dciicon and set 60% opacity
Issue: https://github.com/linuxdeepin/developer-center/issues/8628
> fix: The app preview close button is not clear

- panels/dock/taskmanager/dconfig/org.deepin.ds.dock.taskmanager.json
dde-control-center 改为 org.deepin.dde.control-center
Issues: linuxdeepin/developer-center#8852
> fix: Control Center has not been default docked

- frame/pluginloader.cpp
log: this fix can't load plgins in nixos
> chore: allow follow symlinks when init plugins

- panels/dock/dockplugin/loader/pluginitem.cpp
1.tooltip widget has parent widget
2.plugin's has error sizeHint
Log: as title
> fix: some 1070 tray plugins tooltip not show

- panels/dock/dockplugin/loader/widgetplugin.cpp
- panels/dock/dockplugin/plugin/plugin.cpp
- panels/dock/dockplugin/plugin/plugin.h
bluetooth has this problem.
Log: as title
> fix: Plugin repeatedly calls the itemAdded interface

- frame/qml/PanelPopup.qml
Crashed when accessing attached property in onDestruction.
> fix: crashed when exit

- panels/dock/dockpanel.cpp
fallback to system path if TRAY_DEBUG_PLUGIN_PATH is empty.
> chore: TRAY_DEBUG_PLUGIN_PATH can work in release

- panels/dock/tray/package/tray.qml
Move the mouse between plugins and find that the tooltip is not displayed.
Log: as title
> fix: plugin tooltip not show

- frame/qml/PanelPopup.qml
- frame/qml/PanelToolTip.qml
We can set PanelPopup's window, in somecase, we need output other window instead of default Popup's window.
> feat: support to set PanelPopup's window

- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
- panels/dock/tray/package/DummyDelegate.qml
- panels/dock/tray/package/StashContainer.qml
- panels/dock/tray/package/StashedItemDelegateChooser.qml
- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/package/TrayItemPositioner.qml
- panels/dock/tray/traysortordermodel.cpp
- panels/dock/tray/traysortordermodel.h
为新托盘实现初步拖拽支持。
Log:
----------
注：
1. 当前拖拽仅为非常初步的支持，允许从各个区域拖拽到其它区域，仅在鼠标释放时应用拖拽动作，且拖拽时鼠标无图标指示。
2. 暂未添加对显示/隐藏项目的控制逻辑，后续会另外单独实现/PR。所以快捷面板的拖拽应该要等下一个PR。
3. 向上托盘隐藏区域（StashContainer）目前只是可以拖进去，无法调整顺序/拖拽到指定位置。
> feat: initial drag'n'drop support for new dock tray

- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/traysortordermodel.cpp
- panels/dock/tray/traysortordermodel.h
Log:
-------
cc @18202781743 
是为支持从快捷面板拖拽到托盘的功能的准备。从快捷面板拖拽到tray区域时，携带 `text/x-dde-shell-tray-dnd-surfaceId` MimeType,值为`${pluginId}::${itemKey}` 即可。被拖拽到对应区域的项目若之前已被隐藏，则会被取消隐藏并移动到鼠标 drop 到的位置。若原本就已显示，则只会将原有 item （无论在哪）移动到鼠标 drop 到的位置。
> chore: initial support for hide surface from tray

- panels/dock/tray/quickpanel/CMakeLists.txt
The plugin target with no backing target, so we use PLUGIN_TARGET same with target.
> fix: missing backing lib for quickpanel

- panels/dock/tray/quickpanel/QuickPanelPage.qml
- panels/dock/tray/quickpanel/SubPluginPage.qml
Item's height is set by StackView when pushed a Component, so we add a contentHeight as Item's implicitHeight, and we rebind StackView's height when StackView.activating.
> fix: incorrect height for quickpanel's subplugin

- panels/dock/DockCompositor.qml
- panels/dock/dockplugin/loader/pluginitem.cpp
- panels/dock/dockplugin/loader/widgetplugin.cpp
Call Window's hide instead of widget.
Remove surface from models.
> fix: can't destroy surface when widget hide

- shell/main.cpp
Qt6 find icons will ignore ${GenericDataLocation}/icons/xxx.png
set fallback search paths
Issue: https://github.com/linuxdeepin/developer-center/issues/8413
> fix: can not find icons from share/icons

- panels/dock/taskmanager/x11preview.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/8630
Log: hover预览窗口模糊背景时，预览窗口才出现关闭按钮
> fix: hover预览窗口模糊背景时，预览窗口才出现关闭按钮

- debian/changelog
- panels/dock/package/main.qml
- panels/dock/taskmanager/x11preview.cpp
- panels/dock/taskmanager/x11preview.h
- panels/dock/tray/plugins/uos-ai/uosaiplugin.cpp
* fix: Application preview UI issue(https://github.com/linuxdeepin/developer-center/issues/8801)
* fix: dock panel border color issue(https://github.com/linuxdeepin/developer-center/issues/8342)
* fix: uos-ai icon error(https://github.com/linuxdeepin/developer-center/issues/9363)
* https://github.com/linuxdeepin/developer-center/issues/8413
> chore: bump version to 0.0.25

- panels/dock/launcherItem/package/launcheritem.qml
Coordinate with launchpad positioning, return the icon boundary value
Log:
> feat: Coordinate with launchpad positioning

- frame/qml/PanelToolTip.qml
- panels/dock/clipboarditem/package/clipboarditem.qml
- panels/dock/launcherItem/package/launcheritem.qml
- panels/dock/multitaskview/package/multitaskview.qml
- panels/dock/searchitem/package/searchitem.qml
- panels/dock/taskmanager/package/AppItem.qml
adjust tooltip's position.
only show one tooltip.
adjust ToolTipPanel's width.
> fix: incorrect tooltip's position in non tray area

- frame/qml/PanelToolTip.qml
- panels/dock/tray/package/tray.qml
- panels/dock/tray/quickpanel/PanelTrayItem.qml
- panels/dock/tray/quickpanel/QuickPanel.qml
- panels/dock/tray/quickpanel/quickpanelproxymodel.cpp
- panels/dock/tray/quickpanel/quickpanelproxymodel.h
using tooltip of quickpanel's plugin.
tooltip is reopened, tooltip's visible is binding with readBinding property, and it's assigned in open function.
> fix: missing quickpanel's tooltip

- panels/dock/workspaceitem/package/workspaceitem.qml
Issues: linuxdeepin/developer-center#7984
> fix: the preview image covers the border when non-integer scale factor

- panels/dock/tray/quickpanel/PanelTrayItem.qml
- panels/dock/tray/quickpanel/PluginItem.qml
using HoverHandler to transmit ShellSurfaceItem's hover state. using ColorSelector.hovered to control Palette's state.
> fix: incorrect hovered state when using ShellSurface

- panels/dock/tray/CMakeLists.txt
- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
- panels/dock/tray/package/ActionToggleQuickSettingsDelegate.qml
- panels/dock/tray/package/DummyDelegate.qml
- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/package/TrayItemDelegateChooser.qml
- panels/dock/tray/package/TrayItemPositioner.qml
- panels/dock/tray/package/tray.qml
- panels/dock/tray/trayitempositionmanager.cpp
- panels/dock/tray/trayitempositionmanager.h
- panels/dock/tray/trayitempositionregister.cpp
- panels/dock/tray/trayitempositionregister.h
- panels/dock/tray/traysortordermodel.cpp
- panels/dock/tray/traysortordermodel.h
此提交新增了用于支持非常规尺寸的托盘图标的相关工具类。包括一个管理布
局的类 TrayItemPositionManager 以及用于向此类注册托盘尺寸的另一个类
TrayItemPositionRegister。
------------------
QML 一侧做了初步对接，目前行为是托盘插件可以更新自己的尺寸了，而不再是之前的固定 16*16。另外，Custom 插件目前会被放到 fixed 区域且不允许跨区域拖动，这个行为和需求还有差异，会在后续的 PR 里调整。
> refactor: tray area support custom sized items

- panels/dock/tray/package/tray.qml
- panels/dock/tray/traysortordermodel.cpp
- panels/dock/tray/traysortordermodel.h
现在 DConfig 的变动信号会被监听，hidden 组变化时会更新对应状态并刷新
界面显示顺序。
另外，也调整了拖拽区域的限制，并开始检查 ForceDock 属性。调整后为：
- Custom: 折叠和常显区域随意拖拽
- ForceDock：只能在常显区域拖拽
另外，目前时间插件被特定单独加载到了 fixed 区域。
> chore: watch DConfig valueChanged signal, check surface flag

- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
托盘区域，鼠标光标位置显示拖拽的项目。注意，由于鼠标很容易挡住16*16的图标，
所以拖拽的图标中心调低了一点点以免被挡住。
Log:
> chore: tray area show dragged item at cursor position

- panels/dock/tray/quickpanel/DragItem.qml
Image can load gragToImage's image, and doesn't need to save
image to local.
> chore: using Image to display drag image

- frame/qml/PanelPopupWindow.qml
- panels/dock/dockpositioner.cpp
- panels/dock/dockpositioner.h
following transientParent's screen for PanelPoupWindow.
delay to update position.
> fix: incorrect position for popup in multi screen

- panels/dock/taskmanager/x11preview.cpp
Do not scale when setting icons， Because anti aliasing can cause blurring
Issue: https://github.com/linuxdeepin/developer-center/issues/8649
> fix: blurry application preview icon

- panels/dock/tray/quickpanel/QuickPanelPage.qml
> fix: quickpanel's main page doesn't show when reopened

- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
当 tray item 被拖到托盘区域内后，有可能只显示位置而不显示图标的问题
（因为图标被放到了错误的位置）。这可能是因为 tray 分支 rebase 合入
主干时此段代码被回退了。
Log:
> fix: tray item sometimes shows empty

- panels/dock/tray/quickpanel/DragItem.qml
当给 QuickDragWindow 设置任何 DWindow 属性时，都可能导致 DragEvent 在拖拽过程中被 reject。此处暂时绕过此问题。
Log:
> fix: workaround dxcb/DWindow might cause DragEvent get rejected

- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
not send event to plugin when it's invisible
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/9608
> fix: mouse dance when click ToggleCollapse

- panels/dock/tray/trayitem.cpp
- panels/dock/tray/trayitem.h
as title
Log: as title
Influence: dock or undock function
> fix: dock or undock abnormal function

- panels/dock/tray/package/tray.qml
- panels/dock/tray/trayitempositionmanager.cpp
- panels/dock/tray/trayitempositionmanager.h
首次初始化布局后有概率出现托盘大小/插件位置有偏差的问题，粗略排查和
注册与更新插件位置的时序存在关系。
新增一个辅助接口用来检查布局问题，并在存在问题时触发一次矫正。此新
接口后续可以保留，但程序逻辑中后续不应当依赖此检查来进行布局位置的矫
正行为，例如不应当在设计上依赖此接口来更新布局。
Log:
> fix: workaround incorrect layout at startup

- frame/qml/PanelPopupWindow.qml
- frame/qml/PanelToolTipWindow.qml
it maybe a bug for deepin-kwin, and shadowRadius is set to tooltip.
Issue: https://github.com/linuxdeepin/developer-center/issues/9616
> fix: popup's window display abnormal

- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
- panels/dock/tray/package/ActionShowStashDelegate.qml
- panels/dock/tray/package/ActionToggleCollapseDelegate.qml
- panels/dock/tray/package/StashContainer.qml
- panels/dock/tray/package/StashedItemDelegateChooser.qml
- panels/dock/tray/package/StashedItemPositioner.qml
- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/package/TrayItemDelegateChooser.qml
- panels/dock/tray/package/TrayItemPositioner.qml
- panels/dock/tray/trayitempositionmanager.cpp
- panels/dock/tray/trayitempositionmanager.h
add padding to expand stashitem's width.
add padding for trayitem, trayitem's padding is 4,
and stashitem's padding is 8.
Issue: https://github.com/linuxdeepin/developer-center/issues/9727
> fix: stash container display abnormal

- panels/dock/tray/SurfacePopup.qml
- panels/dock/tray/package/StashContainer.qml
ToolTip's window is show on the popup window, it causes the widget's
widow is received leave event from WM, so we move tooltip to top
of the popup window.
TODO: tooltip's position is not centered.
> fix: tooltip can't show for stash container

- panels/dock/tray/package/tray.qml
Add spacing between the tray applet and the next one
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/9768
> fix: Time zone overlaps with show desktop item

- panels/dock/tray/traysortordermodel.cpp
拖放到 stash 向上箭头图标（的左半部分）上时，原本视为试图移动到此图
标前而拒绝移动行为，现将其视为希望将图标移到托盘 stash 区域内。
这可以在使 stash tray 未被显示出来的情况下也可以将图标移动到托盘区
域内。
Log:
> feat: tray item drop on stash action to move to stash area

- panels/dock/dconfig/org.deepin.ds.dock.tray.json
Issues: linuxdeepin/developer-center#9697
> fix(tray): The input method icon is displayed in the stashed area

- frame/qml/PanelPopupWindow.qml
Remove BypassWindowManagerHint for tooltip's transientParent.
> fix: tooltip is hide

- frame/qml/PanelMenu.qml
Window only can grab mouse after show.
Issue: https://github.com/linuxdeepin/developer-center/issues/9760
> fix: tray's menu can't hide

- panels/dock/tray/package/StashContainer.qml
- panels/dock/tray/package/tray.qml
1. Expanding the acceptance of drop
2. Fix drag and drop after opening the tray, the tray will close automatically
Issue: https://github.com/linuxdeepin/developer-center/issues/9675
> fix: icons cannot be dragged to the stash

- panels/dock/dconfig/org.deepin.ds.dock.tray.json
- panels/dock/tray/traysortordermodel.cpp
Add iscollapsed to save the tray collapsed state
Issue: https://github.com/linuxdeepin/developer-center/issues/9618
> fix: save tray collapsed status

- panels/dock/dockpanel.cpp
Avoid using string concatenation
Log: Increase compatibility of plugin directory
> feat: Increase compatibility of plugin directory

- panels/dock/tray/trayitempositionmanager.cpp
- panels/dock/tray/trayitempositionmanager.h
- panels/dock/tray/trayitempositionregister.cpp
The registered itemsize may change, and the layout needs to be updated when it does.
Issue: https://github.com/linuxdeepin/developer-center/issues/9696
> fix: the item of datetime and showdesktop display overlap

- panels/dock/pluginmanagerextension.cpp
- panels/dock/pluginmanagerextension_p.h
- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
- panels/dock/tray/package/ActionToggleQuickSettingsDelegate.qml
- panels/dock/tray/package/StashedItemDelegateChooser.qml
- panels/dock/tray/package/TrayItemDelegateChooser.qml
- panels/dock/tray/quickpanel/PanelTrayItem.qml
- panels/dock/tray/quickpanel/QuickPanel.qml
Tray item has margins for content, and it's set to loader.
Tray's model has stash data, and it's filter by itemVisible.
it depends on dde-tray-loader.
Issue: https://github.com/linuxdeepin/developer-center/issues/9720
> fix: add margins to extend mouse area for tray item

- frame/qml/PanelPopupWindow.qml
- frame/qml/PanelToolTipWindow.qml
scaling has been processed in kwin for 1070.
Issue: 	https://github.com/linuxdeepin/developer-center/issues/9818
> fix: large radius when exist scaling

- panels/dock/tray/package/ActionShowStashDelegate.qml
- panels/dock/tray/package/tray.qml
Bind the location of the application tray
Issue: https://github.com/linuxdeepin/developer-center/issues/9603
> fix: Application tray position drift

- panels/dock/tray/traysortordermodel.cpp
When the item is hidden, the index needs to be updated
Issue: https://github.com/linuxdeepin/developer-center/issues/9887
> fix: tray container shows blank area when there is only one item

- frame/dsutility.cpp
- frame/qml/PanelMenu.qml
- frame/qml/PanelMenuWindow.qml
- frame/qml/PanelPopup.qml
- frame/qml/PanelPopupWindow.qml
- frame/qml/PanelToolTipWindow.qml
make panelpopup and tooltip work as xdg_popup
log: as title
> fix: panelpopup/tooltip not work as xdg_popup

- panels/dock/tray/package/tray.qml
When the last stashed item exits, the stash container should be closed
Issue: https://github.com/linuxdeepin/developer-center/issues/9830
> fix: the stash container turns into a small ball

- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
plugin item is belong to tray and need to update geometry only itemVisible
is true, otherwise it maybe belong to stash.
> fix: pos conflict between stash and tray

- panels/dock/x11dockhelper.cpp
The wake-up time is too short, causing the animation to not be fully played and resulting in a status error
log: As title
> fix: Sometimes unable to trigger automatic hiding

- frame/qml/PanelPopupWindow.qml
- panels/dock/tray/ShellSurfaceItemProxy.qml
add a check when close surface.
Menu can grab mouse, and close window when ungrab mouse, it causes
tray-loader's surface is invalid.
> fix: tray-loader crashed when reopen menu

- panels/dock/tray/package/TrayItemPositioner.qml
- panels/dock/tray/trayitempositionregister.h
If sectiontype is stashed, the position is not registered
Log: tray item position registration
> fix: tray item position registration

- frame/utility_x11.cpp
- panels/dock/tray/ShellSurfaceItemProxy.qml
Failed to call close because of output's check.
The Menu is reopen when right click the plugin surface, so we
deliverMouseEvent before close window.
Issue: https://github.com/linuxdeepin/developer-center/issues/9959
> fix: popup can't reopen

- panels/dock/showdesktop/package/showdesktop.qml
hovering show-desktop show tooltips, pressing triggers show desktop
Log: hovering show-desktop plugin show tooltips
Influence: hover show desktop plugin
> fix: hovering show-desktop plugin triggers display of desktop

- panels/dock/tray/quickpanel/PanelPluginPage.qml
- panels/dock/tray/quickpanel/PluginItem.qml
as title.
it depends on dde-tray-loader
Issue: https://github.com/linuxdeepin/developer-center/issues/10020
> feat: support active state for quickpanel's item

- panels/dock/package/main.qml
- panels/dock/translations/org.deepin.ds.dock.ts
- panels/dock/translations/org.deepin.ds.dock_az.ts
- panels/dock/translations/org.deepin.ds.dock_bo.ts
- panels/dock/translations/org.deepin.ds.dock_ca.ts
- panels/dock/translations/org.deepin.ds.dock_es.ts
- panels/dock/translations/org.deepin.ds.dock_fi.ts
- panels/dock/translations/org.deepin.ds.dock_fr.ts
- panels/dock/translations/org.deepin.ds.dock_hu.ts
- panels/dock/translations/org.deepin.ds.dock_it.ts
- panels/dock/translations/org.deepin.ds.dock_ja.ts
- panels/dock/translations/org.deepin.ds.dock_ko.ts
- panels/dock/translations/org.deepin.ds.dock_nb_NO.ts
- panels/dock/translations/org.deepin.ds.dock_pl.ts
- panels/dock/translations/org.deepin.ds.dock_pt_BR.ts
- panels/dock/translations/org.deepin.ds.dock_ru.ts
- panels/dock/translations/org.deepin.ds.dock_uk.ts
- panels/dock/translations/org.deepin.ds.dock_zh_CN.ts
- panels/dock/translations/org.deepin.ds.dock_zh_HK.ts
- panels/dock/translations/org.deepin.ds.dock_zh_TW.ts
When the dock is on the left or right, the text is 'Align Top'
Issue: https://github.com/linuxdeepin/developer-center/issues/9947
> fix: The dock translation is incorrect 

- panels/dock/DockCompositor.qml
- panels/dock/pluginmanagerextension.cpp
- panels/dock/pluginmanagerextension_p.h
- panels/dock/tray/quickpanel/QuickPanel.qml
- panels/dock/tray/quickpanel/QuickPanelPage.qml
set minHeight for plugins when creating.
refact sendEventMsg to support sendEvent for one resource.
Issue: https://github.com/linuxdeepin/developer-center/issues/9702
> fix: popup's height isn't enough

- panels/dock/workspaceitem/package/workspaceitem.qml
Close tooltips when switching desktops
Issue: https://github.com/linuxdeepin/developer-center/issues/10030
> fix: Tooltips appear when modifying desktop switching

- panels/dock/tray/traysortordermodel.cpp
仅默认显示固定位置、预制列表中的、应用托盘图标的插件
Issues: linuxdeepin/developer-center#10049
> chore: hide tray plugins by default

- panels/dock/dockpanel.cpp
- panels/dock/x11dockhelper.cpp
When there is no window, modify the hidden mode, and the hidden state is not initialized correctly
Issue: https://github.com/linuxdeepin/developer-center/issues/10107
> fix: Modify smart hide to always hide issues

- frame/qml/PanelPopup.qml
- panels/dock/tray/CMakeLists.txt
- panels/dock/tray/TrayItemSurfacePopup.qml
- panels/dock/tray/package/ActionToggleQuickSettingsDelegate.qml
- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/package/TrayItemDelegateChooser.qml
- panels/dock/tray/package/tray.qml
- panels/dock/tray/quickpanel/QuickPanel.qml
Add TrayItemSurfacePopup to deal with SurfacePopup for tray.
each TrayItem has itself PanelPopup, and then we can switch
to other item by `PopupWindow.currentItem`.
Issue: https://github.com/linuxdeepin/developer-center/issues/10095
> fix: Popup can't switch to other by one click

- frame/utility_x11.cpp
Simulate clicking without converting to X coordinates
Issue: https://github.com/linuxdeepin/developer-center/issues/9964
> fix: mouse position drift

- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
The x and y coordinates of the plugin may be 0, but they have not been updated at this time
Issue:
- https://github.com/linuxdeepin/developer-center/issues/10131
- https://github.com/linuxdeepin/developer-center/issues/9976
> fix: dateTime plugin position error

- panels/dock/package/main.qml
as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/10075
> fix: popup can't close when click empty area for dock

- frame/qml/PanelPopupWindow.qml
- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
Automatically refresh the position of Popupwindow when the available area of the screen changes or when the taskbar position changes
Issue: https://github.com/linuxdeepin/developer-center/issues/10096
> fix: PopupWindow position cannot be refreshed

- panels/dock/tray/quickpanel/QuickPanel.qml
Before displaying sub windows on the shortcut panel, you need to show yourself first
Issue: https://github.com/linuxdeepin/developer-center/issues/10153
> fix: Unable to pop up when modifying network pop ups

- panels/dock/taskmanager/appitem.cpp
Because the corresponding action in deepin-kwin was disabled.
Issue: https://github.com/linuxdeepin/developer-center/issues/10172
Log: Temporarily disable all windows action
> fix: Temporarily disable all windows action

- frame/qml/PanelPopupWindow.qml
- panels/dock/constants.h
- panels/dock/pluginmanagerextension.cpp
- panels/dock/tray/CMakeLists.txt
- panels/dock/tray/SurfacePopup.qml
- panels/dock/tray/SurfaceSubPopup.qml
- panels/dock/tray/TrayItemSurfacePopup.qml
Remove geometry's limits for PluginPopup.
Sync window's geometry to client.
Add SurfaceSubPopup to display subPoup, and SubPopup's geometry
is depends on itself instead of it's transparent geometry.
It depends on dde-tray-loader.
> fix: subMenu can't show

- frame/qml/PanelToolTip.qml
- frame/qml/PanelToolTipWindow.qml
windowRadius： 4 ->8
vPadding: 0->4
textColor:  windowText->brightText
Issue:
- https://github.com/linuxdeepin/developer-center/issues/10005
- https://github.com/linuxdeepin/developer-center/issues/9997
> fix: The padding and rounded corners of the tooltip are incorrect

- panels/dock/dconfig/org.deepin.ds.dock.tray.json
Issues: linuxdeepin/developer-center#10049
> chore: show bluetooth tray icon by default

- panels/dock/dockpanel.cpp
as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10155
Influence: frontendWindowRect size
> fix: dock's frontendWindowRect size is wrong

- frame/private/utility_x11_p.h
- frame/utility_x11.cpp
position of second screen can't only multi devicePixelRatio
when scaling, so we use relative function to simulate motion event.
> fix: incorrect position when ungrab

- CMakeLists.txt
- debian/changelog
> chore: bump version 0.0.34

- panels/dock/tray/package/ActionToggleCollapseDelegate.qml
- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/package/TrayItemPositioner.qml
- panels/dock/tray/traysortordermodel.cpp
> feat: adjust tray collapse animation

- panels/dock/x11dockhelper.cpp
- panels/dock/x11dockhelper.h
update window state after the dock is switched between hidden and shown
Issue: https://github.com/linuxdeepin/developer-center/issues/10222
> fix: dock covered by fullscreen launchpad

- panels/dock/dconfig/org.deepin.ds.dock.tray.json
输入法图标移动到蓝牙图标之前
Issues: linuxdeepin/developer-center#10049
> chore: change the default order of system tray

- debian/dde-shell-example.install
- debian/dde-shell.install
- example/applet-example-data/exampleapplet.cpp
- example/containment-example/examplecontainment.cpp
- example/panel-example/CMakeLists.txt
- panels/dock/CMakeLists.txt
- panels/dock/docksettings.cpp
- panels/dock/taskmanager/CMakeLists.txt
- panels/dock/taskmanager/taskmanagersettings.cpp
- panels/dock/tray/quickpanel/quickpanelproxymodel.cpp
- panels/dock/tray/traysettings.cpp
- panels/dock/tray/traysortordermodel.cpp
> fix!: correct app id used by DConfig

- panels/dock/workspaceitem/package/workspaceitem.qml
Hide workspace when search plugins and clipboard are hidden and displayed on the left
Log: add logic hidden workspace plugin when dock is displayed on the left
> feat: add logic hidden workspace plugin when dock is displayed on the left

- panels/dock/package/main.qml
This reverts commit 3271bdac8830a4d95729b121d814b3c4718dab88.
Issue:
https://github.com/linuxdeepin/developer-center/issues/7943 https://github.com/linuxdeepin/developer-center/issues/8514 https://github.com/linuxdeepin/developer-center/issues/10268 Log: Revert "feat: 调整dock高度时隐藏launchpad"
> Revert "feat: 调整dock高度时隐藏launchpad"

- panels/dock/package/main.qml
Bug of inaccurate coordinate calculation in setting the inner border of the window on the application side
Issue:
- https://github.com/linuxdeepin/developer-center/issues/9686
- https://github.com/linuxdeepin/developer-center/issues/9811
> feat: remove InsideBoxBorder

- frame/layershell/x11dlayershellemulation.cpp
- panels/dock/x11dockhelper.cpp
Screen's topLeft isn't need to multi scaleFactor, it's equal with
X protocol.
Issue: https://github.com/linuxdeepin/developer-center/issues/9925
> fix: incorrect area of exclusion zone for layershell

- panels/dock/tray/SurfacePopup.qml
- panels/dock/tray/SurfaceSubPopup.qml
- panels/dock/tray/TrayItemSurfacePopup.qml
Delay to create subwindow.
app crashed if SurfaceItem isn't in OutPut when exit, so we move
SurfaceItem to OutPut, and the item is managed by OutPut.
> refact: delay to create subwindow

- panels/dock/tray/package/TrayItemPositioner.qml
disable animate when layout is horizontal.
> fix: tray's item overflow when changing dockHeight

- panels/dock/dconfig/org.deepin.ds.dock.tray.json
移动网络插件到固定插件区域
Issues: linuxdeepin/developer-center#10355
> chore: move network plugin to pinned area

- panels/dock/clipboarditem/package/clipboarditem.qml
- panels/dock/searchitem/package/searchitem.qml
- panels/dock/workspaceitem/package/workspaceitem.qml
hide search, clipboard and workspace when leftAlignment
Issue: https://github.com/linuxdeepin/developer-center/issues/10363
> feat: hide search, clipboard and workspace when leftAlignment

- panels/dock/tray/package/tray.qml
- panels/dock/tray/trayitem.cpp
- panels/dock/tray/traysortordermodel.cpp
- panels/dock/tray/traysortordermodel.h
Issues: linuxdeepin/developer-center#10371
> chore: disable hide force-docked item

- panels/dock/package/main.qml
using columnSpacing as leftMargin.
Issue: https://github.com/linuxdeepin/developer-center/issues/10380
> fix: application icon is too close to the left

- panels/dock/OverflowContainer.qml
- panels/dock/taskmanager/appitem.cpp
- panels/dock/taskmanager/itemmodel.cpp
- panels/dock/taskmanager/itemmodel.h
- panels/dock/taskmanager/package/TaskManager.qml
- panels/dock/taskmanager/taskmanager.cpp
- panels/dock/taskmanager/taskmanager.h
拖拽图标至启动器时，拖拽释放前即跟随鼠标位置进行固定，并在释放后提供
图标淡入+放大的动画。
Log:
> feat: animation when drop item from launchpad

- panels/dock/pluginmanagerextension.cpp
- panels/dock/pluginmanagerextension_p.h
- panels/dock/tray/ShellSurfaceItemProxy.qml
add protocol of destroy to release PluginPopup when client has
close the window surface.
add a signal of aboutToDestroy to update shellSurface.
Issue: https://github.com/linuxdeepin/developer-center/issues/10121
> fix: pupup surface doesn't release

- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/treelandwindowmonitor.cpp
- panels/dock/taskmanager/treelandwindowmonitor.h
> feat: tooltip and preview call to treeland

- panels/dock/tray/traysortordermodel.cpp
Each item can only be indexed once
Issue: https://github.com/linuxdeepin/developer-center/issues/10486
> fix: index multiple item in the tray area

- frame/qml/PanelToolTip.qml
as title
关联提交：https://github.com/linuxdeepin/dde-tray-loader/pull/159
Log: as title
> fix: dock is on the right, tooltip popup margins is not 10.

- debian/changelog
bump version 0.0.41
log: as title
> chore: bump version 0.0.42

- panels/dock/pluginmanagerextension.cpp
buffersize is image physical size not logical size
log: as title
> fix: drag size has a devicePixelRatio from quickpanel to tray

- panels/dock/CMakeLists.txt
log: cmake install TARGETS will auto remove reference to /build/
> fix: libdock-plugin.so contains a forbidden reference to /build/

- panels/dock/tray/CMakeLists.txt
- panels/dock/tray/kextracolumnsproxymodel.cpp
- panels/dock/tray/kextracolumnsproxymodel.h
- panels/dock/tray/listtotableproxymodel.cpp
- panels/dock/tray/listtotableproxymodel.h
添加了一个用于将单列 model 的 role 转化为列的代理 model,便于使用
TreeView 可视化单列 model 中各个 role 对应的值。
此代理 model 的第一列仍为原始数据，roles 属性对应原始数据中的
需要映射为单独的列的 role，每个 role 对应一个新的列。
示例用法：
```qml
TreeView {
delegate: TreeViewDelegate {
isTreeNode: false
}
model: DDT.ListToTableProxyModel {
sourceModel: DDT.TraySortOrderModel
roles: [
DDT.TraySortOrderModel.SectionTypeRole,
DDT.TraySortOrderModel.VisibilityRole,
DDT.TraySortOrderModel.VisualIndexRole,
DDT.TraySortOrderModel.SurfaceIdRole,
DDT.TraySortOrderModel.DelegateTypeRole,
DDT.TraySortOrderModel.ForbiddenSectionsRole,
DDT.TraySortOrderModel.IsForceDockRole
]
}
Component.onCompleted: {
setColumnWidth(0, 0) // 隐藏第一列
}
}
```
Log:
> chore: add a helper model for easier debugging

- panels/dock/taskmanager/x11preview.cpp
- panels/dock/taskmanager/x11preview.h
the opacity isn't changed by changing the settings in dcc.
Add the slot to the signal that opacity changes in dcc.
Log:
Bug: https://pms.uniontech.com/bug-view-273041.html
> fix: the opacity of preview window isn't changed

- panels/dock/workspaceitem/xworkspaceworker.cpp
Bug: https://pms.uniontech.com/bug-view-272001.html
Log: WorkspaceItem icon not updated on primary screen changed
> fix: WorkspaceItem icon not updated on primary screen changed

- panels/notification-center/AnimationSettingButton.qml
- panels/notification-center/NormalNotify.qml
- panels/notification-center/OverlapNotify.qml
Disable animation when opening group, only enable aniation when
switching textVisible.
> fix: Remove unnecessary animation for notificationcenter

- frame/qml/PanelToolTipWindow.qml
tooltip radius isn't changed by dcc
Log:
Bug: https://pms.uniontech.com/bug-view-273039.html
> fix: tooltip radius isn't changed

- panels/dock/taskmanager/CMakeLists.txt
- panels/dock/taskmanager/x11utils.cpp
- panels/dock/taskmanager/x11window.cpp
use xcb-icccm instead get property directly
log: as title
> fix: crash on get wmclass

- panels/notification-center/notificationcenterpanel.cpp
- panels/notification/osd/osdpanel.cpp
- shell/CMakeLists.txt
- shell/main.cpp
- shell/shell.cpp
- shell/shell.h
dde-shell register the dbus service, and it's applet only registers
object path.
> feat: support to register dbus service for dde-shell

- panels/dock/taskmanager/x11utils.cpp
> fix: crash on return empty instance and class name

- panels/dock/workspaceitem/xworkspaceworker.cpp
Use dirty fix to run updateData again with timer for delayed screen changing
Bug: https://pms.uniontech.com/bug-view-272001.html Log:
> fix: WorkspaceItem preview image might be incorrect in screen change

- panels/dock/taskmanager/taskmanager.cpp
- panels/dock/taskmanager/taskmanager.h
> fix: crash caused by nullptr or uninitialized ptr

- panels/notification/bubble/bubbleitem.cpp
- panels/notification/bubble/bubblepanel.cpp
- panels/notification/bubble/bubblepanel.h
- panels/notification/bubble/package/BubbleContent.qml
- panels/notification/bubble/package/main.qml
- panels/notification/center/NotifyView.qml
- panels/notification/center/package/main.qml
- panels/notification/server/configs/org.deepin.dde.shell.notification.json
- panels/notification/server/dbusadaptor.cpp
- panels/notification/server/dbusadaptor.h
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notificationmanager.h
Missing enablePreview's settings.
Get AppId by notification's AppName.
Close NotificationCenter when click dock.
Remove notification directly when close notification.
Change the margins of NotificationCenter.
> fix: some bugs for notification

- panels/notification/center/NotifyItemContent.qml
- panels/notification/center/notificationcenterpanel.cpp
- panels/notification/center/notifyaccessor.cpp
- panels/notification/center/notifyaccessor.h
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notificationmanager.h
- panels/notification/server/notificationsetting.cpp
- panels/notification/server/notificationsetting.h
- panels/notification/server/notifyserverapplet.cpp
- panels/notification/server/notifyserverapplet.h
Move notification server to other thread to avoid blocking gui
thread.
notification server has a DB connection to update DataBase, and
it provids update's interface for other applets, notification center
and notification bubble have a default DB connection, then only
query data by DBAccessor.
Add Mutex when getting app infomations, because those interface is
exposed by notification server.
> feat: Move notification server to worker thread

- panels/notification/bubble/bubblemodel.cpp
- panels/notification/bubble/package/BubbleContent.qml
- panels/notification/center/NotifyCenter.qml
- panels/notification/center/NotifyItemContent.qml
- panels/notification/center/NotifyView.qml
- panels/notification/center/notifymodel.cpp
Remove doesn't work when the bubble isn't shown,
NotifyItem isn't deleted.
NotifyHeader is hide by ListView's item.
> fix: bubble doesn't hide

- panels/notification/center/CMakeLists.txt
- panels/notification/center/notificationcenterdbusadaptor.cpp
- panels/notification/center/notificationcenterdbusadaptor.h
- panels/notification/center/notificationcenterpanel.cpp
- panels/notification/osd/CMakeLists.txt
- panels/notification/osd/osddbusadaptor.cpp
- panels/notification/osd/osddbusadaptor.h
- panels/notification/osd/osdpanel.cpp
- panels/notification/osd/osdpanel.h
Register old dbus service to response Shortcut keys.
also we can replace the action in dde-daemon,
https://github.com/linuxdeepin/dde-daemon/blob/master/misc/dde-daemon/keybinding/system_actions.json#L88
> chore: compatible with old notification center

- panels/dock/loadtrayplugins.cpp
plugin run in wayland compositor, while treelane set DDE_CURRENT_COMPOSITOR env. so it will call dtk treeland protocols and crash at that.
log: as title
> fix: plugin crash on treeland

- panels/dock/taskmanager/package/TaskManager.qml
处理Launchpad拖拽固定到Dock时，使用正确的MIME数据
此提交修复占位包需求的遗留问题
此PR目标为维护分支，与 linuxdeepin/dde-launchpad#449 互相依赖。
Log:
Bug: https://pms.uniontech.com/bug-view-279155.html
> fix: use proper launchpad DnD MIME data

- example/applet-example-data/exampleapplet.cpp
- example/applet-example-data/exampleapplet.h
- example/containment-example/examplecontainment.cpp
- example/containment-example/examplecontainment.h
- example/panel-example/examplepanel.cpp
- example/panel-example/examplepanel.h
- frame/CMakeLists.txt
- frame/applet.cpp
- frame/applet.h
- frame/appletbridge.cpp
- frame/appletbridge.h
- frame/appletproxy.cpp
- frame/appletproxy.h
- frame/private/applet_p.h
- frame/private/appletbridge_p.h
- frame/private/appletproxy_p.h
We add AppletProxy to export Applet's signals and slots.
AppletMetaProxy as QObject's router for signals and slots.
> feat: add AppletBridge to connect applets

- frame/appletbridge.cpp
- frame/appletbridge.h
- panels/notification/server/dbusadaptor.cpp
- panels/notification/server/dbusadaptor.h
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notificationmanager.h
- panels/notification/server/notificationsetting.cpp
- panels/notification/server/notificationsetting.h
- panels/notification/server/notifyserverapplet.cpp
Adapt the change of org.deepin.ds.dde-apps.
Add NotificationStateChange signal to expose notification's status.
> fix: Can't get appList for notification

- panels/dock/tray/package/TrayContainer.qml
set dropHoverIndex to default value(-1)  when dropping
Bug: https://pms.uniontech.com/bug-view-279739.html 
Log:
> fix: tray is popped up when a plugin's visible changes

- panels/dock/x11dockhelper.cpp
- panels/dock/x11dockhelper.h
file-desktop window is created recently by dde-shell, but the event filter does not exclude it.
Bug: https://pms.uniontech.com/bug-view-276731.html 
Log:
> fix: task isn't hidden when it's in hidden mode

- debian/control
- debian/dde-shell.install
- panels/notification/CMakeLists.txt
- panels/notification/common/dbaccessor.cpp
Create db file if not exist.
Add dependencies when packaging.
Task: https://pms.uniontech.com/task-view-366403.html
> fix: db file can't create firstly for notification

- panels/dock/taskmanager/treelandwindow.cpp
- panels/dock/taskmanager/treelandwindow.h
should send window state changed to appitem
log: as title
bug: https://pms.uniontech.com/bug-view-280555.html
> fix: treeland unable to activate next window

- frame/containment.h
Can't find appletitemmodel.h when using Q_OBJECT to inherit form
DPanel.
Task: https://pms.uniontech.com/task-view-365879.html
> fix: compile error

- shell/CMakeLists.txt
- shell/shell.cpp
- shell/treelandoutputwatcher.cpp
- shell/treelandoutputwatcher.h
Since Wayland has no concept of primaryScreen. We create a TreelandOutputWatcher to update the client's primaryScreen information
log: as title
> feat: use treeland output manager to update primaryScreen info

- example/bridge-example/CMakeLists.txt
> fix: remove find DDEShell in bridge example

- panels/dock/showdesktop/CMakeLists.txt
- panels/dock/showdesktop/showdesktop.cpp
- panels/dock/showdesktop/showdesktop.h
- panels/dock/showdesktop/treelandwindowmanager.cpp
- panels/dock/showdesktop/treelandwindowmanager.h
On treeland call treeland protools to show desktop
log: as title
> feat: show desktop adapted to treeland

- debian/control
dde-shell depneds dde-tray-loader not libdde-shell
log: as title
> chore: correct wrong dep

- panels/dock/taskmanager/taskmanager.cpp
Recognition errors caused by using prefixes instead of full matches
log: as title
> fix: correct window recognition errors

- panels/dock/OverflowContainer.qml
- panels/dock/taskmanager/CMakeLists.txt
qt6.8 default size policy has changed, temporarily modify the minimum size
log: as title
> fix: dock with no item inside

- example/CMakeLists.txt
默认不构建/打包bridge示例，避免安装了example包的用户看到任务栏多出来
的组件而感到困惑。
Log:
> chore: don't ship the bridge example by default

- frame/CMakeLists.txt
设置属性应当使用 "${PUBLIC_HEADERS}" 确保所有 header 都被设置恰当属性
> fix: headers not installed correctly

- applets/dde-apps/amappitem.cpp
- applets/dde-apps/amappitemmodel.cpp
- applets/dde-apps/appgroup.cpp
- applets/dde-apps/appgroup.h
- applets/dde-apps/appgroupmanager.cpp
- applets/dde-apps/appgroupmanager.h
- applets/dde-apps/appitem.cpp
- applets/dde-apps/appitem.h
- applets/dde-apps/appitemmodel.cpp
- applets/dde-apps/appitemmodel.h
- applets/dde-apps/appsapplet.cpp
- applets/dde-apps/appsapplet.h
- panels/notification/server/notificationsetting.cpp
调整 AppGroupModel 与 AMAppItemModel 的关系，其它部分暂未调整。
变化说明：
1. 目前决定复用 AppGroupManager，后续可能需要补充一些实现（目前没处理分组内容为空后清除分组的行为，也没自动为所有未分组的应用分配分组）
2. AppGroupManager 不再是单例
3. AMAppItem 和 AppGroup 现在都是 AppItem 的子类了，便于后续直接组合对应的两个模型
4. AMAppsModel 不再提供分组信息（后续在组合模型提供，分组信息的数据源仍由 AppGroupManager 管理）
后续待调整内容：
1. 暴漏的 appsModel 转为一个组合模型，同时包含这两个模型的数据
5. 处理应用组的初始化、位置信息更新等行为，确保每个应用总是有分组信息
> refactor: adjust relationship between AppGroupModel and AMAppItemModel

- applets/dde-apps/appitem.h
> fix: should also remove virtual API from appitem.h

- panels/dock/taskmanager/x11preview.cpp
use FastTransformation instead of SmoothTransformation
Bug: https://pms.uniontech.com/bug-view-285265.html
Log: Blurry X11 Window previews
> fix: Blurry X11 Window previews

- panels/dock/showdesktop/package/showdesktop.qml
Disable tooltip until hover off
Bug: https://pms.uniontech.com/bug-view-281843.html
Log: Avoid showing tooltip while clicking show-desktop button
> fix: Avoid showing tooltip while clicking show-desktop button

- panels/dock/multitaskview/CMakeLists.txt
- panels/dock/multitaskview/multitaskview.cpp
- panels/dock/multitaskview/multitaskview.h
- panels/dock/multitaskview/treelandmultitaskview.cpp
- panels/dock/multitaskview/treelandmultitaskview.h
> feat: call treeland protocols to show multitaskview

- panels/notification/center/CMakeLists.txt
- panels/notification/center/NormalNotify.qml
- panels/notification/center/NotifyItemContent.qml
- panels/notification/center/NotifyStyle.qml
ContentItem's height is not large enough.
Bug: https://pms.uniontech.com/bug-view-283509.html
> fix: incomplete display of time for notification

- panels/notification/center/NotifyCenter.qml
- panels/notification/center/NotifyStaging.qml
- panels/notification/center/notificationcenterpanel.cpp
- panels/notification/center/notifyaccessor.cpp
- panels/notification/center/notifyaccessor.h
- panels/notification/center/package/main.qml
Stage is still received notification before it's display,
We don't receive notification when it's invisible,
and clear the model when NotificationCenter closed.
Bug: https://pms.uniontech.com/bug-view-283969.html
> fix: error displayed in stage for notification

- panels/notification/center/NotifyAction.qml
- panels/notification/center/NotifyHeader.qml
- panels/notification/center/NotifyItemContent.qml
- panels/notification/center/notifyaccessor.cpp
- panels/notification/center/notifyaccessor.h
- panels/notification/center/notifymodel.cpp
- panels/notification/center/notifymodel.h
- panels/notification/center/notifystagingmodel.cpp
- panels/notification/center/notifystagingmodel.h
- panels/notification/common/dataaccessor.h
- panels/notification/common/dbaccessor.cpp
- panels/notification/server/notificationmanager.cpp
AppName maybe is empty string, so we use an string to represent
AllApp.
Adjust action's background.
Task: https://pms.uniontech.com/task-view-366403.html
> fix: empty string can't represent AllApp for notification

- panels/dock/taskmanager/treelandwindowmonitor.cpp
when dock hide shell surface will destoried and old preview context will be invalid
log: as title
> fix: use invalid shellsurface to show preview

- panels/notification/center/NotifyCenter.qml
- panels/notification/center/package/main.qml
as title.
Bug: https://pms.uniontech.com/bug-view-283749.html
> fix: incorrect height of notificationCenter for notification

- panels/dock/dockpanel.cpp
- panels/dock/dockpanel.h
- panels/notification/bubble/package/main.qml
- panels/notification/center/package/main.qml
Using screenName instead of position to adjust dock and notification
is on the same screen.
Bug: https://pms.uniontech.com/bug-view-284191.html
> fix: incorrect position of panel for notification

- panels/notification/bubble/bubblemodel.cpp
- panels/notification/bubble/bubblemodel.h
- panels/notification/common/dbaccessor.cpp
- panels/notification/common/dbaccessor.h
- panels/notification/server/configs/org.deepin.dde.shell.notification.json
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notificationsetting.cpp
> chore: code review modification suggestions

- applets/dde-apps/amappitemmodel.cpp
- applets/dde-apps/amappitemmodel.h
- applets/dde-apps/appgroup.cpp
- applets/dde-apps/appgroup.h
- applets/dde-apps/appgroupmanager.cpp
- applets/dde-apps/appgroupmanager.h
添加和暴露组相关 API 给 QML，供后续使用。
review 注意：
看是否有哪些接口是潜在需要使用的接口但没有暴露，或者哪些接口不合理等。
> refactor: add and and export group-related APIs to QML

- frame/containment.cpp
- frame/private/containment_p.h
- frame/qmlengine.cpp
- panels/notification/common/dataaccessor.h
- panels/notification/common/dbaccessor.cpp
- panels/notification/common/dbaccessor.h
- panels/notification/common/notifyentity.cpp
- panels/notification/server/notificationmanager.cpp
as title.
Log: as title
pms: Task-365879
> fix: memory lack for shell

- panels/dock/CMakeLists.txt
- panels/dock/dockpositioner.cpp
- panels/dock/dockpositioner.h
Remove the dependency of DockPanel for DockPlugin.
Log: as title.
> fix: incorrect dependency for DockPositioner

- panels/notification/common/dbaccessor.cpp
as title
Log: ActionInvoked returned wrong id
Bug: https://pms.uniontech.com/bug-view-283561.html
> fix: ActionInvoked returned wrong id

- panels/notification/bubble/bubblemodel.cpp
- panels/notification/bubble/bubblemodel.h
- panels/notification/bubble/package/Bubble.qml
Add a list to delay remove Bubble when it's timeout.
Remove bubble when delayRemoveBubble changed.
pms: Bug-283823
> fix: bubble closed when it's still hovering for notification

- applets/dde-shutdown/CMakeLists.txt
- applets/dde-shutdown/shutdownapplet.cpp
- applets/dde-shutdown/shutdownapplet.h
- applets/dde-shutdown/treelandlockscreen.cpp
- applets/dde-shutdown/treelandlockscreen.h
- example/CMakeLists.txt
- example/lockscreen-example/CMakeLists.txt
- example/lockscreen-example/package/main.qml
- example/lockscreen-example/package/metadata.json
> feat: add lockscreen protocol for ShutdownApplet

- debian/dde-shell.install
as title
Log: dde-shutdown is not install
> fix: dde-shutdown is not install

- panels/notification/bubble/package/main.qml
- panels/notification/center/package/main.qml
as title.
pms: Bug-283995,Bug-283991
> fix: theme type can't change for notification

- frame/models/kextracolumnsproxymodel.cpp
Upstream change: kitemmodels [1a5e6e8dc6cf8656c0a66a63c3acb541978c9e08](https://github.com/KDE/kitemmodels/commit/1a5e6e8dc6cf8656c0a66a63c3acb541978c9e08)
> KExtraColumnsProxyModel: port to Qt 6.8's QIdentityProxyModel::setHandleSourceLayoutChanges

- frame/qml/PanelMenuWindow.qml
- frame/qml/PanelPopupWindow.qml
- frame/qml/PanelToolTipWindow.qml
adjust popup window flags
log: as title
> fix: popup has no focus on treeland

- panels/notification/server/dbusadaptor.cpp
- panels/notification/server/dbusadaptor.h
> chore: dde notification dbus adaptor export standard interface

- panels/notification/bubble/bubbleitem.cpp
- panels/notification/plugin/NotifyItemContent.qml
as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-286813.html
> fix: Display bubble icon normally

- debian/changelog
> chore: bump to 1.99.8

- debian/changelog
- frame/CMakeLists.txt
- frame/plugin/CMakeLists.txt
- frame/plugin/qmlplugin.cpp
- frame/popupwindow.cpp
- frame/popupwindow.h
- frame/qml/PanelPopupWindow.qml
- panels/dock/package/main.qml
Qt popup get event from other window, so it's necessary to make dock can get focus. And add a PopupWindow to handle Popup auto hide.
log: as title
> fix: popup can not auto hide on treeland

- debian/changelog
> chore: change version to 1.99.9

- panels/dock/taskmanager/taskmanager.cpp
修复部分场景下可能导致错误识别 desktopId,导致任务栏图标被隐藏.
Log:
> fix: empty icon on task manager in some cases

- panels/dock/dockhelper.cpp
- panels/dock/dockhelper.h
- panels/dock/taskmanager/abstractwindowmonitor.h
- panels/dock/taskmanager/taskmanager.cpp
- panels/dock/taskmanager/taskmanager.h
- panels/dock/taskmanager/treelandwindow.cpp
- panels/dock/taskmanager/treelandwindow.h
- panels/dock/taskmanager/treelandwindowmonitor.cpp
- panels/dock/taskmanager/treelandwindowmonitor.h
- panels/dock/waylanddockhelper.cpp
- panels/dock/waylanddockhelper.h
- panels/dock/x11dockhelper.cpp
- panels/dock/x11dockhelper.h
pms:
BUG-263325
BUG-278961
Log: Auto hide dde-dock on window fullscreen in Wayland
> feat: Auto hide dde-dock on window fullscreen in Wayland

- panels/notification/bubble/bubblemodel.cpp
- panels/notification/bubble/bubblemodel.h
as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-290185.html
> fix: Setting notifications number less than 3, do not display overlay

- panels/dock/CMakeLists.txt
> chore: Remove strong build dependency of dcc

- debian/control
Log: Add missing dependencies for libdde-shell-dev
> chore: Add missing dependencies for libdde-shell-dev

- panels/notification/common/dbaccessor.cpp
- panels/notification/server/dbusadaptor.cpp
- panels/notification/server/notificationmanager.cpp
> fix: Avoid empty notification.

- panels/notification/bubble/bubbleitem.cpp
- panels/notification/bubble/package/NormalBubble.qml
- panels/notification/center/notifyitem.cpp
- panels/notification/common/notifyentity.cpp
- panels/notification/common/notifyentity.h
- panels/notification/server/dbusadaptor.cpp
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notificationmanager.h
Default action maybe have text, and it's actionId is default.
Remove entity when manually closing it before timeout.
CloseNotification can't work.
pms: BUG-290767
> fix: default action can't work for notification

- panels/notification/common/dbaccessor.cpp
- panels/notification/common/dbaccessor.h
- panels/notification/server/notificationmanager.h
- panels/notification/server/notifyserverapplet.cpp
Move updating database of Applet from caller thread to Manager's
thread.
> fix: database maybe corrup

- CMakeLists.txt
- debian/control
- frame/popupwindow.cpp
- frame/qml/PanelPopupWindow.qml
- panels/dock/CMakeLists.txt
- panels/dock/DockCompositor.qml
- panels/dock/dockpanel.cpp
- panels/dock/dockpanel.h
- panels/dock/loadtrayplugins.cpp
- panels/dock/package/main.qml
- panels/dock/pluginmanagerextension.cpp
- panels/dock/pluginmanagerextension_p.h
- panels/dock/taskmanager/treelandwindowmonitor.cpp
- panels/dock/tray/ShellSurfaceItemProxy.qml
- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
- 修复popup不完整问题
问题在于QQUickWindow的contentItem尺寸和QQUickWindow没有保持一致导致的，理论上应该是一致的，但是实际出现了不一致的情况，所以临时使用了Binding将两者尺寸绑定到一起并加了FIXME
- 修复popup缩放问题
popup的缩放之前是通过环境变量设置过去的，但是treeland下支持动态改动缩放，导致缩放不能动态的更着变更。
1. 去掉环境变量使用wayland 分数缩放协议来做缩放的动态调整
2. 通过协议提交尺寸，而不是通过buffer来计算尺寸，因为output级别的缩放仅支持整数缩放而不支持分数缩放，会导致尺寸计算不太正确，所以直接使用协议设置对应的尺寸过来。依赖dde-tray-loader 对应的提交https://github.com/linuxdeepin/dde-tray-loader/pull/211
> Popup size

- frame/popupwindow.cpp
- frame/popupwindow.h
When dragging occurs, the MouseReleaseEvent outside the popup will be a dropEvent,and the window will no longer be closed.
log: as title
pms: BUG-291969
> fix: launchpad hide at dropEvent

- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/traysortordermodel.cpp
- panels/dock/tray/traysortordermodel.h
as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-266651.html
> fix: Disable dropping of already displayed plugin.

- panels/dock/taskmanager/dconfig/org.deepin.ds.dock.taskmanager.json
as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-266869.html
> chore: Modify professional os taskManager fixed application

- debian/control
- panels/dock/dconfig/org.deepin.ds.dock.tray.json
- panels/dock/loadtrayplugins.cpp
- panels/dock/loadtrayplugins.h
1.Divide plugins into three groups(selfMaintenance,application,other) 2.single process support to start multiple plugins
Log: as title
Bug: https://pms.uniontech.com/bug-view-283901.html
> chore: TrayLoader single process support to start multiple plugins

- panels/dock/taskmanager/itemmodel.cpp
- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/package/TaskManager.qml
- panels/dock/taskmanager/taskmanager.cpp
- panels/dock/taskmanager/taskmanager.h
将应用图标拖出任务栏时，即取消固定。
PMS: BUG-284079 BUG-291165
> chore: drag out from dock to remove icon

- panels/notification/osd/windoweffect/package/main.qml
只有在触发windoweffect的osd时才触发特效调节
pms: TASK-368711
> fix: windoweffect osd triggered abnormally

- frame/popupwindow.cpp
- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
- panels/dock/tray/quickpanel/PluginItem.qml
close popup later, beacause dock still get click event
log: as title
> fix: unable to hide popup click twice on treeland

- panels/notification/server/dbusadaptor.cpp
- panels/notification/server/notificationmanager.cpp
std::numeric_limits<unit>::max() cause dbus_message protocol error.
> fix: dbus_message protocol error for notification

- panels/notification/bubble/bubbleitem.cpp
- panels/notification/bubble/bubbleitem.h
- panels/notification/bubble/bubblemodel.cpp
- panels/notification/bubble/bubblemodel.h
- panels/notification/bubble/bubblepanel.cpp
- panels/notification/center/notifyitem.cpp
- panels/notification/center/notifystagingmodel.cpp
- panels/notification/center/notifystagingmodel.h
- panels/notification/common/dataaccessor.h
- panels/notification/common/dbaccessor.cpp
- panels/notification/common/dbaccessor.h
- panels/notification/common/notifyentity.cpp
- panels/notification/common/notifyentity.h
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notifyserverapplet.cpp
- panels/notification/server/notifyserverapplet.h
Notify server adapt replace notify, it will override old notify
both DB data and timeout data, and emit NotificationStateChanged.
pms: BUG-289863
> fix: stage doens't adapt replace notify for notification

- panels/notification/plugin/NotifyItemContent.qml
Action is display in contentItem default, it avoids to hiding
Combobox's popup when the count of Action is more than two.
> fix: drop strongInteractive of action for notification

- panels/dock/tray/package/TrayContainer.qml
- panels/dock/tray/quickpanel/DragItem.qml
as title
Log: as title
pms: BUG-293871
> fix: tray plugin can not drag

- panels/notification/CMakeLists.txt
- panels/notification/bubble/bubblemodel.cpp
- panels/notification/bubble/bubblemodel.h
- panels/notification/bubble/bubblepanel.cpp
- panels/notification/bubble/bubblepanel.h
- panels/notification/bubble/package/NormalBubble.qml
- panels/notification/center/NormalNotify.qml
- panels/notification/center/NotifyStaging.qml
- panels/notification/center/NotifyViewDelegate.qml
- panels/notification/center/OverlapNotify.qml
- panels/notification/center/notifymodel.cpp
- panels/notification/center/notifymodel.h
- panels/notification/center/notifystagingmodel.cpp
- panels/notification/center/notifystagingmodel.h
- panels/notification/common/notifysetting.cpp
- panels/notification/common/notifysetting.h
- panels/notification/plugin/NotifyItem.qml
- panels/notification/plugin/NotifyItemContent.qml
- panels/notification/server/configs/org.deepin.dde.shell.notification.json
as title
Log: as title
pms: BUG-289409
> chore: Add notification content row number configuration

- panels/dock/taskmanager/package/AppItem.qml
Use Qt's new retainWhileLoading to solve the problem of Image loading flickering instead of using a fixed size to scale to the current size
log: as title
> fix: Problems caused by the fixed size of the taskbar icon

- panels/notification/server/configs/org.deepin.dde.shell.notification.json
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notificationmanager.h
as title
Log: as title
pms: BUG-294157
> fix: Notification appName is not translated

- panels/notification/center/notifystagingmodel.cpp
> fix: missing removed of stage's notify for notification

- panels/dock/taskmanager/abstractwindowmonitor.cpp
- panels/dock/taskmanager/rolecombinemodel.cpp
The model's boundary processing error causes the data to be changed out of bounds
log: as title
pms: BUG-292027
cherry-pick https://github.com/linuxdeepin/dde-shell/pull/929
> fix: WeChat and WXChat are recognized as the same

- panels/dock/dockhelper.cpp
- panels/dock/x11dockhelper.cpp
- panels/dock/x11dockhelper.h
1. when hideModeChanged to start show/hide timer
2. make the dock's rect is the original size so that the window rect obtained by xcb can correctly calculate whether it overlaps
log: as title
pms: BUG-293825
> fix: dock will not hide on hideModeChanged by dbus

- frame/layershell/x11dlayershellemulation.cpp
- frame/layershell/x11dlayershellemulation.h
Changing screen layout may not change the geometry of the screen binded to dock. (For example, the screen stay on top or left without resolution changed) So, connect slot to all screens instead.
pms: BUG-292677
Log: Changing screen layout might make dock exclusion zone incorrect
> fix: Changing screen layout might make dock exclusion zone incorrect

- applets/dde-shutdown/shutdownapplet.cpp
> fix: x11 shutdown plugin menu function

- applets/dde-shutdown/shutdownapplet.cpp
- applets/dde-shutdown/shutdownapplet.h
> fix: x11 shutdown menu can not lock screen

- frame/layershell/x11dlayershellemulation.cpp
- frame/layershell/x11dlayershellemulation.h
> fix: Remove position change timer on X11Emulation

- debian/changelog
> chore: bump version to 1.99.13

- panels/notification/bubble/package/main.qml
- panels/notification/center/package/main.qml
Adjust UI for notification
Using exclusionZone to Adatp incorrect margin in treeland.
Drop DWindow's platformhandle.
> fix: incorrect margin in treeland for notification

- panels/dock/tray/quickpanel/SubPluginPage.qml
> fix: error max height of embed plugin popup

- panels/notification/server/notificationmanager.cpp
Fallback to appName if AppName is null fetching from settings.
> fix: can't query Notify for notification

- debian/changelog
> chore: bump version to 1.99.14

- frame/popupwindow.cpp
- panels/dock/pluginmanagerextension.cpp
The size of the popup window is not initialized and limited to the maximum value, resulting in excessive memory usage due to excessive size in some cases
log: as title
> fix: Video memory explosion caused by randomly clicking on dock plugins

- panels/dock/taskmanager/package/TaskManager.qml
修复拖拽任务栏上的应用图标时，图标拖拽位置和实际位置可能错位的问题。
> fix: drag offset on dock taskmanager

- panels/notification/center/package/main.qml
as title
Log: as title
Bug: BUG-294647
> fix: notification-center auto hide when clicked other window

- panels/notification/bubble/bubblepanel.cpp
- panels/notification/bubble/bubblepanel.h
- panels/notification/bubble/package/NormalBubble.qml
- panels/notification/center/NormalNotify.qml
- panels/notification/center/NotifyStaging.qml
- panels/notification/center/NotifyViewDelegate.qml
- panels/notification/center/OverlapNotify.qml
- panels/notification/center/notifyaccessor.cpp
- panels/notification/center/notifyaccessor.h
- panels/notification/center/notifystagingmodel.cpp
- panels/notification/center/notifystagingmodel.h
- panels/notification/plugin/NotifyItem.qml
- panels/notification/plugin/NotifyItemContent.qml
- panels/notification/server/notificationmanager.cpp
Dismissed notify doesn't move to notification center.
Disable dismissed of overlap notification for notification center.
> fix: missing dismissed to close notify for notication

- debian/control
> chore: update section to DDE in debian/control

- panels/notification/CMakeLists.txt
- panels/notification/bubble/bubblemodel.cpp
- panels/notification/bubble/bubblepanel.cpp
- panels/notification/center/notificationcenterpanel.cpp
- panels/notification/center/notifyitem.cpp
- panels/notification/center/notifyitem.h
- panels/notification/center/notifystagingmodel.cpp
- panels/notification/common/dataaccessor.h
- panels/notification/common/dataaccessorproxy.cpp
- panels/notification/common/dataaccessorproxy.h
- panels/notification/common/dbaccessor.cpp
- panels/notification/common/dbaccessor.h
- panels/notification/common/memoryaccessor.cpp
- panels/notification/common/memoryaccessor.h
- panels/notification/server/notificationmanager.cpp
add cache to stage Bubble, and save it to DB only when processed.
pms: BUG-290145
> fix: stage notify doesn't remove when exit for notification

- panels/dock/dcc-dock-plugin/qml/main.qml
> fix(dcc-dock-plugin): dockmode change to alignleft

- panels/notification/bubble/package/main.qml
Window has default radius in x11, so CloseButton will be clip,
We should set windowRadius to zero by PlatformHandle
> fix: closeButton was cliped for notification

- frame/qml/PanelPopupWindow.qml
Different plugins have different panelPopup sizes. clicking different plugin, this prevents the incorrect size popup display when you click to close the popup.
Log: as title
> fix: reset width and height when popup closed

- frame/qml/PanelPopup.qml
> fix: last content is displayed

- panels/dock/taskmanager/dconfig/org.deepin.ds.dock.taskmanager.json
This reverts commit 4c9cc5a2c96e2fbbad879a13bbfdb17d2ca06313.
> Revert "chore: Modify professional os taskManager fixed application"

- panels/dock/taskmanager/treelandwindow.cpp
Need emit stateChanged() signal when window is going to be destroyed
pms: BUG-297479
Log: Dock will not update hide state when window is destroyed
> fix: Dock will not update hide state when window is destroyed

- applets/dde-shutdown/package/metadata.json
- panels/notification/server/notificationmanager.cpp
- panels/notification/server/notificationmanager.h
Support to call dde-shell's plugin function by notification's action.
e.g: call org.deepin.ds.dde-shell's Shutdown.
```
gdbus call --session --dest=org.freedesktop.Notifications \
--object-path=/org/freedesktop/Notifications \
--method=org.freedesktop.Notifications.Notify \
"test" 0 "" 'deepin-dde-shell-action' '' \
'["shutdown", "shutdown"]' \
'{"deepin-dde-shell-action-shutdown":<"{\"pluginId\":\"org.deepin.ds.dde-shutdown\",\"method\":\"requestShutdown\",\"arguments\":[\"Shutdown\" ]}">}' \
0
```
> feat: Add deepin-shell-action for notification

- frame/layershell/x11dlayershellemulation.cpp
It caused other screen's maxed window hide when show the window,
and it's only a flag when exclusion zone is less zero in x11.
pms: TASK-365879
> fix: incorrect exclusionZone in x11

- panels/dock/tray/package/TrayContainer.qml
Dragged the plugin from the quick panel, but it was not dropped into the tray area; instead, it was docked into the tray area
as title
Log: as title
pms: BUG-284079
> fix: plugin docked into tray area

- panels/dock/taskmanager/package/AppItem.qml
Remove it because of consuming performance.
pms: BUG-365879
> fix: drop BoxShadow for Attention animation

- panels/notification/server/notificationmanager.cpp
DataAccessorProxy::instance() is an static object, and we should release
it in server applet.
pms: BUG-366403
> fix: access wild pointer for notificationcenter

- panels/dock/searchitem/searchitem.h
由于全局搜索未适配 layershell，导致全局搜索框的位置可能不正确。在
全局搜索适配前，临时为 treeland 环境禁用任务栏上的全局搜索图标。
Log:
> chore: temporary disable grand-search icon for wayland

- panels/dock/tray/quickpanel/DragItem.qml
修改后拖拽时将不会实时改变overlayWindow的尺寸，避免了拖拽时产生的不流畅效果。但旧的基于全窗口模糊的效果实现将无法使用。
补充了部分关于开启模糊时拖拽事件不生效的原因的描述。
Log:
> fix: jittering when dragging quick action applet

- debian/control
- panels/dock/pluginmanagerextension.cpp
- panels/dock/pluginmanagerextension_p.h
Sync theme information to qwayland client.
pms: BUG-301149
> feat: adapt to qwayland for DPlatformTheme

- example/CMakeLists.txt
- example/applet-widget-example/CMakeLists.txt
- example/applet-widget-example/exampleapplet.cpp
- example/applet-widget-example/exampleapplet.h
- example/applet-widget-example/package/metadata.json
it's useful to debug.
pms:TASK-365879
> chore: add applet-widget example

- panels/notification/server/notificationmanager.cpp
as title
Log: as title
Pms: BUG-297399
> fix: start a timer in another thread

- frame/layershell/x11dlayershellemulation.cpp
- panels/dock/dockhelper.cpp
- panels/dock/dockhelper.h
1. SmartHide mode does not automatically hide
2. KeepHidden mode should not be hidden when a subwindow show
Log: pms-302819
> fix: Error with SmartHidden and KeepHidden modes of dock

- panels/dock/taskmanager/abstractitem.h
- panels/dock/taskmanager/appitem.cpp
- panels/dock/taskmanager/appitem.h
- panels/dock/taskmanager/desktopfileabstractparser.cpp
- panels/dock/taskmanager/desktopfileabstractparser.h
- panels/dock/taskmanager/desktopfileamparser.cpp
- panels/dock/taskmanager/desktopfileamparser.h
- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/package/TaskManager.qml
- panels/dock/taskmanager/taskmanager.cpp
- panels/dock/taskmanager/taskmanager.h
拖拽文件到图标上以打开新实例并将拖拽的文件作为参数.
注:仅实现了拖拽打开行为.并未进行拖拽到图标上则激活现有窗口的实现.
PMS: BUG-275395
------
另注：若合并关于任务栏组合功能的分支，此功能仍需要重新做。
> feat: drop to dock task icon to launch with uri

- panels/dock/dockhelper.cpp
- panels/dock/dockhelper.h
- panels/dock/dockpanel.cpp
- panels/dock/dockpanel.h
- panels/dock/taskmanager/package/AppItem.qml
- panels/dock/taskmanager/package/TaskManager.qml
- panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
- panels/dock/tray/package/DummyDelegate.qml
Add contextDragging state to DockPanel
AppItem and TrayPlugin will update when dragged and dropped
pms: BUG-289207
pms: BUG-289205
> fix: Dragging an application will hide the dock

- panels/dock/taskmanager/x11windowmonitor.cpp
In auto hide mode, when the mouse moves to the preview window, the dock automatically hides X11WindowMonitor set transient parent
Log: as title
> fix: The dock automatically hides

- example/bridge-example/package/appletitem.qml
- panels/dock/taskmanager/package/TaskManager.qml
修复任务栏图标数量过多时,新增图标后,图标大小仍未更新的问题.
PMS: BUG-289225
Log:
> fix: item size not updated when taskbar item count was changed

- debian/changelog
Changes:
* fix: record replaced notification to DB (Bug: 296235)
* fix: Error with SmartHidden and KeepHidden modes of dock (Bug: 302819)
* feat: drop to dock task icon to launch with uri (Bug: 275395)
* fix: Staging notifications cannot disappear after timeout (Bug: 303331)
* fix: Incorrect application layout menu display content (Bug: 289221, 286541, 286553)
* fix: Notifications not displayed in the center cannot disappear after timeout (Bug: 303295)
* fix: Staging notifications cannot disappear after timeout (Bug: 303331)
* fix: Dragging an application will hide the dock (Bug: 289207, 289205)
* fix: add offset to quick panel drag item to avoid cursor cover icon (Bug: 293867)
* fix: The dock automatically hides
* fix: item size not updated when taskbar item count was changed (Bug: …
> chore: bump version to 1.99.22

- applets/dde-appearance/appearanceapplet.cpp
it's a bug for dtk in DDBusExtendedAbstractInterface, which is
not initialize value when using userCache.
pms:BUG-297195
> fix: invalid cache for opacity

- panels/dock/pluginmanagerextension.cpp
> chore: quickpanel's theme doesn't change with setting

- panels/notification/server/notificationmanager.cpp
as title
Log: as title
Pms: BUG-304355
> fix: call to LockFront1 dbus service is blocked in wayland

- cmake/DDEShellPackageMacros.cmake
> chore: translation target display issue in qtcreator

- panels/dock/package/main.qml
as title
Log: as title
Pms: BUG-302889
> fix: remove dock left part space

- panels/dock/CMakeLists.txt
- panels/dock/pluginmanagerextension.cpp
> fix: num-lock can't enable

- panels/dock/dockpanel.cpp
在启动器为显示状态时,直接拖拽dock边缘迅速调整dock高度会导致dock高度变回拖拽前的高度,表现行为即dock显示不完整或dock内组件使用的高度与dock自身高度不符.
根音是启动器的隐藏会触发dock隐藏状态属性变化的信号(无论是否真的变化了),此属性绑定了调整dock窗口高度的动画,动画中修改了窗口的实际高度.
由于当前仅以最保守的形式进行bug修复,此处仅添加了属性是否实际变化的检查,并仅在真的变化时才发变化的信号.此部分对应的写法应当后续改掉.
PMS: BUG-303541, BUG-303155
> fix: task area might have incorrect height after resize in some cases

- debian/changelog
Changelog:
* fix: task area might have incorrect height after resize in some cases
(BUG: 303541, 303155)
Log:
> chore: release dde-shell 1.99.27

- debian/changelog
as title
Log: bump version to 1.99.28
> chore: bump version to 1.99.28

- panels/dock/DockCompositor.qml
- panels/dock/pluginmanagerextension.cpp
- panels/dock/pluginmanagerextension_p.h
- panels/dock/tray/quickpanel/QuickPanel.qml
Bug: https://pms.uniontech.com/bug-view-272277.html
Log: Receive close quick panel requests from plugins
cherry-pick from https://github.com/linuxdeepin/dde-shell/pull/807
> feat: Receive close quick panel requests from plugins

- panels/dock/taskmanager/dconfig/org.deepin.ds.dock.taskmanager.json
as title
Log: as title
Pms: story-38175
> chore: modify default docked items

- panels/dock/api/old/org.deepin.dde.daemon.Dock1.xml
- panels/dock/dockdbusproxy.cpp
- panels/dock/dockdbusproxy.h
- panels/dock/taskmanager/taskmanager.cpp
- panels/dock/taskmanager/taskmanager.h
add interface for deepin-apps.
Log:
> feat: add activeWindow Dbus interface.

- panels/notification/center/notifystagingmodel.cpp
- panels/notification/common/dataaccessorproxy.cpp
1. Changed BubbleNotifyItem to AppNotifyItem in NotifyStagingModel for
better naming consistency
2. Simplified DataAccessorProxy by removing redundant source validity
checks
3. Improved entity routing logic with clearer conditions
4. Added proper source initialization in DataAccessorProxy constructor
5. Enhanced removeEntity() to check entity validity before removal
6. Streamlined clear() and removeEntityByApp() to only operate on source
The changes improve code maintainability and reduce redundant
checks while maintaining the same functionality. The naming change
from BubbleNotifyItem to AppNotifyItem better reflects the item's
purpose, and the data access logic simplification makes the code more
straightforward and less error-prone.
refactor: 更新通知处理和数据访问逻辑
1. 在 NotifyStagingModel 中将 …
> refactor: update notification handling and data access logic

- panels/dock/pluginmanagerextension_p.h
Added QML_ELEMENT and QML_UNCREATABLE macros to PluginSurface and
PluginPopup classes to resolve QString::arg compilation warnings. These
annotations explicitly declare the QML element registration and prevent
QML instantiation, ensuring proper type registration and eliminating the
missing argument warnings during compilation.
Log: Fixed compilation warnings related to QML type registration
Influence:
1. Verify that the dock plugin compiles without warnings
2. Test that PluginSurface and PluginPopup classes still function
correctly in C++ context
3. Confirm that QML cannot instantiate these classes as intended
4. Check that all existing dock functionality remains unaffected
fix: 添加QML注解消除编译警告
为PluginSurface和PluginPopup类添加QML_ELEMENT和QML_UNCREATABLE宏，解决 …
> fix: add QML annotations to eliminate compilation warnings

- panels/notification/center/NotifyCenter.qml
- panels/notification/center/NotifyViewDelegate.qml
- panels/notification/center/package/main.qml
- panels/notification/plugin/NotifyStyle.qml
Changed width calculation from hardcoded values to use
NotifyStyle.contentItem.width for consistent styling
Added proper scrollbar width calculation in NotifyCenter to account for
scrollbar presence
Updated main window width calculation to include proper padding handling
Fixed anchor margins and right constraints to ensure proper layout with
dynamic width
Added contentPadding property for better maintainability of spacing
values
Log: Fixed notification center layout issues with dynamic width
calculation
Influence:
1. Test notification center display with different content widths
2. Verify scrollbar appears correctly and doesn't cause layout issues
3. Check that all notification items maintain consistent width
4. Test window resizing behavior and content alignment
5. Verify margins and …
> fix: adjust notification center width calculation

- panels/notification/center/NotifyCenter.qml
Fixed scrollbar positioning issue in notification center by:
1. Removed unused DS style import that was causing conflicts
2. Added right anchor and rightMargin to properly position the content
area
3. Removed explicit width calculation that was causing misalignment
4. Maintained height calculation based on maxViewHeight and viewHeight
The scrollbar was incorrectly positioned due to hardcoded width
calculations that didn't account for proper layout constraints. By
using anchor-based layout with appropriate margins instead of explicit
width calculations, the scrollbar now positions correctly within the
notification center panel.
Log: Fixed notification center scrollbar positioning issue
Influence:
1. Open notification center and verify scrollbar appears correctly
positioned
2. Test …
> fix: adjust notification center scrollbar position
