linuxdeepin/dde-shell

frame/pluginloader.cpp
frame/pluginloader.h
shell/main.cpp

load all root applet by default.
Issue: https://github.com/linuxdeepin/developer-center/issues/5965

feat: load all root applet by default

---

frame/appletitem.cpp
frame/pluginloader.cpp

Panel's Applet is fallbacked to window.

fix: failed fetch Applet attached property for Panel

---

frame/pluginloader.cpp
frame/pluginloader.h
shell/main.cpp

don't load some applet.
list all applet by tree struct.

feat: don't load disabled applet by option

---

CMakeLists.txt
frame/CMakeLists.txt
frame/layershell/dlayershellwindow.cpp
frame/layershell/x11dlayershellemulation.cpp
frame/layershell/x11dlayershellemulation.h

emulate layershell on x11
log: add x11 layershell eamulation

feat: add x11 layershell emulation

---

debian/control

missing some qml packages.
Issue: https://github.com/linuxdeepin/developer-center/issues/6026

fix: missing some dependices for debian

---

frame/pluginloader.cpp
frame/pluginloader.h

Output error message if the plugin loads failed.

feat: add plugin's check

---

debian/dde-shell-example.install
example/applet-example-data/exampleapplet.cpp
example/applet-example-data/exampleapplet.h
example/panel-example/CMakeLists.txt
example/panel-example/examplepanel.cpp
example/panel-example/examplepanel.h
example/panel-example/org.deepin.ds.example.json
example/panel-example/package/metadata.json
frame/applet.cpp
frame/applet.h
frame/containment.cpp
frame/containment.h
frame/panel.cpp
frame/panel.h
frame/pluginloader.cpp
frame/pluginloader.h
panels/osd/audio/audioapplet.cpp
panels/osd/audio/audioapplet.h
panels/osd/brightness/brightnessapplet.cpp
panels/osd/brightness/brightnessapplet.h
panels/osd/displaymode/displaymodeapplet.cpp
panels/osd/displaymode/displaymodeapplet.h
panels/osd/kblayout/kblayoutapplet.cpp
panels/osd/kblayout/kblayoutapplet.h
panels/osd/osdpanel.cpp
panels/osd/osdpanel.h
shell/main.cpp

using `return value` to filter some applets.

feat: filter unload applet

---

panels/osd/osdpanel.cpp
shell/main.cpp

feat: add signal handler to release applets

---

debian/changelog

chore: update changelog to 0.0.1

---

example/applet-example-data/exampleapplet.cpp
example/applet-example-data/exampleapplet.h
example/applet-example/package/main.qml
example/containment-example/CMakeLists.txt
example/containment-example/examplecontainment.cpp
example/containment-example/examplecontainment.h
example/panel-example/examplepanel.cpp
example/panel-example/org.deepin.ds.example.json
frame/CMakeLists.txt
frame/applet.cpp
frame/applet.h
frame/appletdata.cpp
frame/appletdata.h
frame/containment.cpp
frame/containment.h
frame/panel.cpp
frame/panel.h
frame/pluginloader.cpp
frame/pluginloader.h
frame/private/applet_p.h
frame/private/containment_p.h
panels/dock/dockpanel.cpp
panels/dock/dockpanel.h
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h
panels/osd/osdpanel.cpp
panels/osd/osdpanel.h

Add AppletGroup to manage what applet will be load.
Issue: https://github.com/linuxdeepin/developer-center/issues/6245

feat: support multi instance with same Applet

---

debian/control
debian/dde-shell.install
panels/CMakeLists.txt
panels/notification/CMakeLists.txt
panels/notification/bubblemodel.cpp
panels/notification/bubblemodel.h
panels/notification/notificationinterproxy.cpp
panels/notification/notificationinterproxy.h
panels/notification/notificationpanel.cpp
panels/notification/notificationpanel.h
panels/notification/package/Bubble.qml
panels/notification/package/BubbleAction.qml
panels/notification/package/BubbleContent.qml
panels/notification/package/NormalBubble.qml
panels/notification/package/OverlayBubble.qml
panels/notification/package/main.qml
panels/notification/package/metadata.json
panels/notification/test.sh

TODO: notification replace.
Issue: https://github.com/linuxdeepin/developer-center/issues/6095

feat: add notification

---

panels/dock/package/main.qml

Use triple equal operator to compare values.
Log: use triple equal operator

optimize: use triple equal operator

---

frame/pluginfactory.cpp

chore: correct typos in pluginfactory.cpp

---

example/applet-example-data/package/main.qml
frame/applet.cpp
frame/applet.h

Export parent property to qml.

feat: support to find parent applet

---

panels/notification/notificationinterproxy.cpp
panels/notification/notificationinterproxy.h
panels/notification/notificationpanel.cpp

add processed type and logic about it
Log: Add Processed type in notification

chore: Add Processed type

---

frame/layershell/dlayershellwindow.h

exclusionZone is int32_t type not uint32_t
log: fix typo

fix: exclusionZone type error

---

.reuse/dep5
debian/dde-shell.install
misc/dde-shell-plugin@.service.in
misc/dde-shell@.service.in
panels/dock/package/metadata.json
panels/notification/package/metadata.json
panels/osd/package/metadata.json
shell/CMakeLists.txt
shell/main.cpp

feat: support systemd to manage single plugin

---

example/applet-example-data/package/main.qml
frame/appletitem.cpp
frame/panel.cpp
frame/qmlengine.cpp

store applet in contextProperty.

fix: can't access Applet for non Item

---

example/applet-example-data/package/main.qml
frame/containmentitem.cpp
frame/panel.cpp
frame/panel.h
frame/plugin/qmlplugin.cpp

`Panel` attached property to access the nearest `DPanel`.

feat: support to access the nearest Panel

---

debian/control

fix: missing systemd package

---

debian/control

fix: missing labs package

---

panels/notification/package/BubbleContent.qml
panels/notification/package/NormalBubble.qml
panels/notification/package/OverlayBubble.qml
panels/notification/package/main.qml
panels/notification/test.sh

New notification

---

debian/changelog
debian/control

chore: update changelog to 0.0.2

---

frame/layershell/x11dlayershellemulation.cpp

Add margin calculations into the equation
log: as title

fix: unable set margins when anchor three sides in xorg

---

panels/dock/OverflowContainer.qml
panels/dock/launcherItem/package/launcheritem.qml
panels/dock/package/main.qml
panels/dock/showdesktop/package/showdesktop.qml
panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/StatusIndicator.qml
panels/dock/taskmanager/package/TaskManager.qml

Use list view to display items.
Log: fix item container geometry

fix: item container geometry

---

debian/changelog
debian/dde-shell.install
debian/libdde-shell.install
panels/dock/CMakeLists.txt

- fix: missing files for dock plugin
- chore: update changelog to 0.0.3

fix dock missing install qmlplugin

---

frame/CMakeLists.txt

Optimize cmake list files.
Log: optimize cmake

chore: optimize cmake

---

example/applet-example-data/package/main.qml
frame/ddeshell_qml.qrc
frame/panel.cpp
frame/panel.h
frame/plugin/qmlplugin.cpp
frame/private/panel_p.h
frame/qml/PanelToolTip.qml
frame/qmlengine.cpp
frame/qmlengine.h

feat: add PanelToolTip

---

panels/dock/taskmanager/appitemmodel.cpp
panels/dock/taskmanager/appitemmodel.h
panels/dock/taskmanager/package/TaskManager.qml

Modify data model when dropped.
Log: modify data model in dnd

feat: modify data model in dnd

---

panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/appitem.h

Mark getters const so they can be used in const functions.
Log: mark getters const

chore: mark getters const

---

panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/AppItemPalette.qml
panels/dock/taskmanager/package/StatusIndicator.qml
panels/dock/taskmanager/package/TaskManager.qml

Use MouseArea instead. TapHandler may be not so complete.
Log: fix drag handler still active when finished

fix: drag handler still active when finished

---

example/applet-example-data/exampleapplet.cpp
example/applet-example-data/exampleapplet.h
example/applet-example-data/package/main.qml
frame/appletitem.cpp
frame/appletitem.h
frame/pluginmetadata.cpp
frame/pluginmetadata.h
frame/private/appletitem_p.h

We use Binding to execute some code in onCompleted before step.
Add rvalue constructor for PluginMetaData.

feat: add sub Applet's property example

---

debian/changelog
debian/control
panels/dock/CMakeLists.txt
panels/dock/dockplugin/loader/CMakeLists.txt
panels/dock/taskmanager/CMakeLists.txt

chore: update changelog to 0.0.4

---

panels/dock/taskmanager/abstractwindowmonitor.h
panels/dock/taskmanager/api/wayland-protocols/treeland-foreign-toplevel-manager-v1.xml
panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h
panels/dock/taskmanager/waylandwindow.cpp
panels/dock/taskmanager/waylandwindow.h
panels/dock/taskmanager/waylandwindowmonitor.cpp
panels/dock/taskmanager/waylandwindowmonitor.h
panels/dock/taskmanager/x11windowmonitor.cpp
panels/dock/taskmanager/x11windowmonitor.h

add application preview in treeland
log: as title

feat: add dock application preview in treeland

---

panels/dock/CMakeLists.txt
panels/dock/dockdbusproxy.cpp
panels/dock/dockdbusproxy.h
panels/dock/dockpanel.cpp
panels/dock/dockplugin/plugin/CMakeLists.txt
panels/dock/taskmanager/CMakeLists.txt

dock has defined some func but not implemneted them
log: as title

fix: undefined symbols

---

debian/dde-shell.install
panels/dock/CMakeLists.txt
panels/dock/dconfig/org.deepin.ds.dock.json
panels/dock/docksettingsdconfig.cpp
panels/dock/taskmanager/CMakeLists.txt
panels/dock/taskmanager/desktopfileamparsersettings.cpp
panels/dock/taskmanager/taskmanagersettings.cpp

install ds.dock dconfigs
log: as title

chore: fix missing ds.dock dconfigs

---

panels/dock/tray/package/tray.qml

use a timer to show tootip later
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/6906

fix: tooltip reparent error

---

panels/dock/package/main.qml

make dock window transparent and set radius for "in desktop" direction corners
log: as title

feat: set dock radius for dock window in Fashion mode

---

panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/package/main.qml
panels/dock/tray/package/tray.qml

1. remove window opacity
2. make DWindowRadius to 0
3. adjust tray size and spacing size
log: as title

chore: adjust dock ui

---

panels/dock/slidingpanel/package/slidingpanel.qml

fix: tmp make a fixed timedate replace slidingpanel

---

panels/dock/dockpanel.h
panels/dock/package/main.qml

fix: remove some warnings during runtime

---

panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/slidingpanel/package/slidingpanel.qml
panels/dock/tray/package/tray.qml

1. make tmp timedate transparent
2. adjust tray icon size and spacing
log: as title

fix: adjust some ui

---

archlinux/PKGBUILD

chore: add archlinux build for obs

---

debian/changelog

bump version 0.0.5
log: as title

chore: release 0.0.5

---

panels/dock/package/main.qml

fix: resize area size

---

panels/dock/package/main.qml

fix: mouse_a not exist

---

panels/dock/package/main.qml

fix: dock window flash when resize

---

panels/dock/OverflowContainer.qml
panels/dock/tray/package/tray.qml

feat: hide tray animation

---

frame/qml/PanelPopup.qml
frame/qml/PanelToolTip.qml

fix: size of popupwindow not changed

---

panels/dock/taskmanager/x11window.cpp

fix: call isEmpty not empty

---

debian/control

fix: add build-dep for dock preview

---

frame/layershell/x11dlayershellemulation.cpp

according to qt doc bottom/right will returns top/left + height/width - 1;
log: as title

fix: one pixel left when anchor to side

---

panels/dock/taskmanager/abstractitem.h
panels/dock/taskmanager/abstractwindow.h
panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/appitem.h
panels/dock/taskmanager/itemmodel.cpp
panels/dock/taskmanager/itemmodel.h
panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/BeatAnimation.qml
panels/dock/taskmanager/package/LaunchAnimation.qml
panels/dock/taskmanager/package/TaskManager.qml
panels/dock/taskmanager/waylandwindow.cpp
panels/dock/taskmanager/waylandwindow.h
panels/dock/taskmanager/x11window.cpp
panels/dock/taskmanager/x11window.h

Add attention event handling and display for the appitem
Add appitem launch effect
Log: Add attention event handling and display for the appitem

feat: Add attention event handling and display for the appitem

---

panels/dock/CMakeLists.txt
panels/dock/package/DockPartAppletModel.qml
panels/dock/package/main.qml
panels/dock/workspaceitem/CMakeLists.txt
panels/dock/workspaceitem/package/metadata.json
panels/dock/workspaceitem/package/workspaceitem.qml
panels/dock/workspaceitem/workspaceitem.cpp
panels/dock/workspaceitem/workspaceitem.h
panels/dock/workspaceitem/workspacemodel.cpp
panels/dock/workspaceitem/workspacemodel.h
panels/dock/workspaceitem/xworkspaceworker.cpp
panels/dock/workspaceitem/xworkspaceworker.h

feat: Workspace item
Workspace item
Log: Workspace item
Influence: Workspace item

feat: Workspace item

---

panels/dock/taskmanager/x11windowmonitor.cpp
panels/dock/taskmanager/x11windowmonitor.h

window just unmap when minimized without compositoer not destoried
log: as title

fix: dock item destoried on x11 without window effect

---

frame/pluginloader.cpp
frame/pluginloader.h
frame/qmlengine.cpp

We should load builtin plugins firstly.

fix: incorrent loaded order in debug mode

---

shell/appletloader.cpp

fix: can't filter root applet when loaded failed

---

example/applet-example-data/package/main.qml
frame/CMakeLists.txt
frame/applet.cpp
frame/dsqmlglobal.cpp
frame/plugin/qmlplugin.cpp
frame/pluginloader.cpp
frame/pluginloader.h
frame/pluginmetadata.cpp
frame/pluginmetadata.h
frame/private/dsqmlglobal_p.h
shell/appletloader.cpp
shell/main.cpp

Add an virtual root applet to manage client's root applet.
Add DS singleton object.

feat: support to get other root applet

---

panels/dock/tray/frame/controller/dockitemmanager.cpp
panels/dock/tray/frame/dockapplet.cpp
panels/dock/tray/frame/window/tray/widgets/snitrayitemwidget.cpp
panels/dock/tray/plugins/display/brightnessadjwidget.cpp
panels/dock/tray/plugins/display/displaysettingwidget.cpp
panels/dock/tray/plugins/sound/sounddeviceswidget.cpp

log: widget incomplete
issue: https://github.com/linuxdeepin/developer-center/issues/7704

fix: fix brightness widget display is incomplete

---

panels/dock/dockpanel.cpp
panels/dock/dockpanel.h
panels/dock/package/main.qml

fix: dock menu not shown

---

panels/dock/taskmanager/dconfig/org.deepin.ds.dock.taskmanager.json
panels/dock/taskmanager/desktopfileamparser.cpp
panels/dock/taskmanager/taskmanager.cpp

feat: check am app is really valid

---

panels/dock/launcherItem/package/launcheritem.qml
panels/dock/package/main.qml

Modify the launchpad location.

feat: adapt to launchpad plugin

---

debian/changelog

bump version 0.0.7
log: as title

chore: bump version 0.0.7

---

panels/dock/api/old/org.deepin.dde.daemon.Dock1.xml
panels/dock/dockdbusproxy.cpp
panels/dock/dockdbusproxy.h
panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h

Implement corresponding functionality and logic.
Log: Fix the failure to send from the launcher to the dock
Influence: send to the dock
Issue: https://github.com/linuxdeepin/developer-center/issues/7700

fix: Fix the failure to send from the launcher to the dock.

---

panels/dock/launcherItem/package/launcheritem.qml
panels/dock/package/main.qml
panels/dock/taskmanager/package/AppItem.qml

Scale until resize over, then set source size.

fix: icon blink when resize

---

panels/dock/taskmanager/x11preview.cpp
panels/dock/taskmanager/x11preview.h

use listview rewrite x11 preview
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7706

fix: x11 preview not fit screen

---

panels/dock/tray/plugins/system-monitor/CMakeLists.txt

fix: wrong install path

---

applets/dde-appearance/appearanceapplet.cpp

feat: limit opacity from dde-appearance

---

panels/dock/taskmanager/desktopfileamparser.cpp

init m_amIsAvaliable when am is unavaliable
log: as title

fix: dock appitem get default icon when start before am

---

panels/dock/tray/frame/quickproxywidget.cpp
panels/dock/tray/frame/quickproxywidget.h
panels/dock/tray/frame/window/components/datetimedisplayer.cpp
panels/dock/tray/frame/window/docktraywindow.cpp
panels/dock/tray/plugins/pluginmanager/quicksettingcontainer.cpp

perf: refresh the widget when appropriate

---

panels/dock/clipboarditem/package/clipboarditem.qml
panels/dock/searchitem/package/searchitem.qml

fix: searchitem and clipboarditem size

---

panels/dock/taskmanager/waylandwindow.cpp
panels/dock/taskmanager/x11preview.cpp
panels/dock/taskmanager/x11preview.h
panels/dock/taskmanager/x11window.cpp

Check if index is valid at the cursor.

fix: preview crash when drag and release outside

---

panels/dock/tray/plugins/system-monitor/CMakeLists.txt

log: https://pms.uniontech.com/story-view-30767.html \
暂时屏蔽系统监视器插件，点击动作
改为打开系统监视器主程序

fix: disable popup plugin for system-monitor

---

debian/changelog

bump version 0.0.8
log: as title

chore: bump version 0.0.8

---

applets/dde-appearance/appearanceapplet.cpp

as title.
issue: https://github.com/linuxdeepin/developer-center/issues/7976

fix: nullptr for dde-appearance

---

panels/dock/searchitem/searchitem.cpp

Log: https://github.com/linuxdeepin/developer-center/issues/3402

chore: avoid hardcode path

---

panels/dock/searchitem/package/searchitem.qml

chore: tiny code format

---

panels/dock/clipboarditem/package/clipboarditem.qml
panels/dock/package/main.qml
panels/dock/searchitem/package/searchitem.qml

1. add hover
2. add leftmargin
log: as title

feat: adjust search and clipboard ui

---

panels/dock/tray/plugins/media/mediaplayermodel.h

log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7858

fix: player icon not update

---

panels/dock/package/main.qml
panels/dock/translations/org.deepin.ds.dock.ts
panels/dock/translations/org.deepin.ds.dock_az.ts
panels/dock/translations/org.deepin.ds.dock_bo.ts
panels/dock/translations/org.deepin.ds.dock_ca.ts
panels/dock/translations/org.deepin.ds.dock_es.ts
panels/dock/translations/org.deepin.ds.dock_fi.ts
panels/dock/translations/org.deepin.ds.dock_fr.ts
panels/dock/translations/org.deepin.ds.dock_hu.ts
panels/dock/translations/org.deepin.ds.dock_it.ts
panels/dock/translations/org.deepin.ds.dock_ja.ts
panels/dock/translations/org.deepin.ds.dock_ko.ts
panels/dock/translations/org.deepin.ds.dock_nb_NO.ts
panels/dock/translations/org.deepin.ds.dock_pl.ts
panels/dock/translations/org.deepin.ds.dock_pt_BR.ts
panels/dock/translations/org.deepin.ds.dock_ru.ts
panels/dock/translations/org.deepin.ds.dock_uk.ts
panels/dock/translations/org.deepin.ds.dock_zh_CN.ts
panels/dock/translations/org.deepin.ds.dock_zh_HK.ts
panels/dock/translations/org.deepin.ds.dock_zh_TW.ts

update menu text and translate
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7955

fix: rename mode to Alignment

---

panels/dock/taskmanager/abstractwindow.h
panels/dock/taskmanager/itemmodel.h
panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h
panels/dock/taskmanager/waylandwindow.cpp
panels/dock/taskmanager/waylandwindow.h
panels/dock/taskmanager/x11utils.cpp
panels/dock/taskmanager/x11utils.h
panels/dock/taskmanager/x11window.cpp
panels/dock/taskmanager/x11window.h

add setWindowIconGeometry for set window_icon_gemeotry property
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7887

fix: not set window icon gemeotry for window

---

debian/changelog

bump version 0.0.9
log: as title

chore: bump version 0.0.9

---

panels/dock/workspaceitem/package/workspaceitem.qml

set Image to preserve aspect ratio
Log:

fix: workspace item not preserving aspect ratio

---

panels/dock/api/old/org.deepin.dde.daemon.Dock1.xml
panels/dock/constants.h
panels/dock/dockdbusproxy.cpp
panels/dock/dockdbusproxy.h
panels/dock/dockpanel.cpp
panels/dock/package/main.qml

1. dockDbusProxy proxy resize dock to setDockSize
2. forward dockpanel changed signal to dbus
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7999

fix: dde-control-center unable to set dockSize

---

panels/dock/taskmanager/CMakeLists.txt
panels/dock/taskmanager/api/amdbus/org.desktopspec.ObjectManager1.xml
panels/dock/taskmanager/api/amdbus/org.desktopspec.ProcessGuesser1.xml
panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/desktopfileabstractparser.cpp
panels/dock/taskmanager/desktopfileabstractparser.h
panels/dock/taskmanager/desktopfileamparser.cpp
panels/dock/taskmanager/desktopfileamparser.h
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h

add AM ObjectManager bus signal
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7978

fix: appitem not remove when uninstalled

---

panels/dock/searchitem/package/searchitem.qml
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_az.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_bo.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_ca.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_es.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_fi.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_fr.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_hu.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_it.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_ja.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_ko.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_nb_NO.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_pl.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_pt_BR.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_ru.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_uk.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_zh_CN.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_zh_HK.ts
panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_zh_TW.ts
panels/dock/translations/org.deepin.ds.dock_ca.ts
panels/dock/translations/org.deepin.ds.dock_fi.ts
panels/dock/translations/org.deepin.ds.dock_hu.ts
panels/dock/translations/org.deepin.ds.dock_pl.ts
panels/dock/translations/org.deepin.ds.dock_ru.ts
panels/dock/translations/org.deepin.ds.dock_uk.ts
panels/dock/translations/org.deepin.ds.dock_zh_CN.ts
panels/dock/translations/org.deepin.ds.dock_zh_HK.ts
panels/dock/translations/org.deepin.ds.dock_zh_TW.ts

log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8080

fix: Alignment without translate

---

panels/dock/searchitem/package/searchitem.qml

issue: https://github.com/linuxdeepin/developer-center/issues/8083
log: as title

fix: not show search menu

---

panels/dock/tray/frame/quickproxywidget.cpp
panels/dock/tray/frame/quickproxywidget.h
panels/dock/tray/frame/window/docktraywindow.cpp
panels/dock/tray/frame/window/docktraywindow.h

as title
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8039

fix: datetime plugin not update

---

panels/dock/launcherItem/package/launcheritem.qml

Watch launchpad's rootObject changed and update it's pos.

fix: null rootObject of launchpad

---

panels/dock/taskmanager/x11preview.cpp
panels/dock/taskmanager/x11preview.h

* 窗口大小自动扩展
* 限制预览图高度（横向）/宽度（纵向），等比缩放
Issues: linuxdeepin/developer-center#7975

fix: Task Manager preview size is not correct

---

panels/dock/launcherItem/package/launcheritem.qml
panels/dock/package/main.qml
panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/BeatAnimation.qml

Dragging the dock to adjust the height causes the app icon to become blurry
Log: dock height change causes the app icon to be blurred
issue: https://github.com/linuxdeepin/developer-center/issues/7988
issue: https://github.com/linuxdeepin/developer-center/issues/8077
Influence: Icon clarity

fix: dock height change causes the app icon to be blurred

---

panels/dock/workspaceitem/package/workspaceitem.qml

set listview interactive to false
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8120

fix: workspace can interactive

---

panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/appitem.h
panels/dock/taskmanager/x11preview.cpp
panels/dock/taskmanager/x11preview.h

use toolbutton instead of iconbutton
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7937

fix: x11 preview hover without background

---

frame/qml/PanelToolTip.qml

Set mouseArea to dciicon
Issue: https://github.com/linuxdeepin/developer-center/issues/8095

fix: TooTip can't show when hover from left to right

---

debian/changelog

chore: bump version 0.0.11

---

panels/dock/taskmanager/x11preview.cpp

QLabel 宽度计算不对
Issues: linuxdeepin/developer-center#8147

fix: preview title not elided

---

panels/dock/package/main.qml

refact: update ColorSelector family for dock panel

---

panels/dock/taskmanager/x11preview.cpp

* 添加背景色
* 限制最大宽度（横向）和最大高度（竖向）
* 添加深色模式的颜色
Issues: linuxdeepin/developer-center#7975

feat: optimize preview style

---

panels/dock/CMakeLists.txt
panels/dock/multitaskview/CMakeLists.txt
panels/dock/multitaskview/multitaskview.cpp
panels/dock/multitaskview/multitaskview.h
panels/dock/multitaskview/package/metadata.json
panels/dock/multitaskview/package/multitaskview.qml
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_az.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_bo.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ca.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_es.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_fi.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_fr.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_hu.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_it.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ja.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ko.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_nb_NO.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_pl.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_pt_BR.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ru.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_uk.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_zh_CN.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_zh_HK.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_zh_TW.ts
panels/dock/tray/frame/util/dockpopupwindow.cpp
panels/dock/tray/frame/util/dockpopupwindow.h

add toggle workspace item
Log:

chore: add toggle workspace item

---

frame/qml/PanelToolTip.qml
panels/dock/CMakeLists.txt
panels/dock/DockPalette.qml
panels/dock/OverflowContainer.qml
panels/dock/clipboarditem/package/clipboarditem.qml
panels/dock/package/main.qml
panels/dock/searchitem/package/searchitem.qml
panels/dock/taskmanager/package/AppItemPalette.qml
panels/dock/workspaceitem/package/workspaceitem.qml

1. adjust dock drak mode background color
2. fix window indicator border color
3. fix workspaceitem unabel to see at dark mode
3. adjust Toolutton Background
4. adjust tooltip top and botton padding
log: as title

fix: dock ui adjust

---

frame/qml/PanelPopupWindow.qml

windowRadius doesn't multi devicePixelRatio by WM.

chore: adjust radius for ToolTips

---

panels/dock/multitaskview/package/multitaskview.qml

update scale use Panel.rootObject.dockItemMaxSize
Log:

fix: multitaskview not scale realtime

---

panels/dock/package/main.qml
panels/dock/tray/frame/package/tray.qml

Issue: https://github.com/linuxdeepin/developer-center/issues/8181

fix: set cursor shape for dock and tray

---

shell/CMakeLists.txt
shell/InWindowBlur.qml
shell/main.cpp
shell/override_dtkdeclarative_qml.qrc
shell/shell.cpp
shell/shell.h

Override Dtk's InWindowBlur,
add overlay above BackdropBlitter for InWindowBlur.
Issue: https://github.com/linuxdeepin/developer-center/issues/8211

fix: transparent windows cannot be blurred

---

frame/qml/PanelPopupWindow.qml
panels/dock/DockPalette.qml
panels/dock/OverflowContainer.qml
panels/dock/clipboarditem/package/clipboarditem.qml
panels/dock/package/main.qml
panels/dock/searchitem/package/searchitem.qml
panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/TaskManager.qml
panels/dock/taskmanager/package/WindowIndicator.qml
panels/dock/taskmanager/x11preview.cpp
panels/dock/workspaceitem/package/workspaceitem.qml

1. adjust popup radius
2. adjust OverflowContainer
3. remote toolbutton insideBorder
log: as title

feat: adjust ui

---

panels/dock/multitaskview/package/multitaskview.qml
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_az.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_bo.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ca.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_es.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_fi.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_fr.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_hu.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_it.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ja.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ko.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_nb_NO.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_pl.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_pt_BR.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_ru.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_uk.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_zh_CN.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_zh_HK.ts
panels/dock/multitaskview/translations/org.deepin.ds.dock.multitaskview_zh_TW.ts

change ts to Multitasking View
Issue: https://github.com/linuxdeepin/developer-center/issues/8225 Log:

fix: multitaskview ts

---

panels/dock/taskmanager/package/TaskManager.qml

Set keys for drop area.
Log: let drop area check the keys

optimize: let drop area check the keys

---

frame/pluginloader.cpp
panels/dock/taskmanager/desktopfileabstractparser.cpp
panels/dock/tray/frame/dockapplet.cpp
panels/dock/tray/frame/quickproxywidget.cpp
panels/dock/tray/plugins/bluetooth/componments/bluetoothapplet.cpp
panels/dock/tray/plugins/bluetooth/componments/bluetoothapplet.h

desktopfile is null in some times.

chore: nullptr check

---

panels/dock/taskmanager/x11preview.cpp

Get window image information only once during showPreview.
Issue: https://github.com/linuxdeepin/developer-center/issues/8095

fix: application preview stuttering.

---

shell/InWindowBlur.qml

chore: missing lincense

---

panels/dock/translations/org.deepin.ds.dock_zh_CN.ts
panels/dock/translations/org.deepin.ds.dock_zh_HK.ts
panels/dock/translations/org.deepin.ds.dock_zh_TW.ts

modify ts file for "Bottom" and "Top".
Log: modify ts file
issue: https://github.com/linuxdeepin/developer-center/issues/8270
Influence: translation display

chore: modify ts file

---

shell/main.cpp
shell/shell.cpp
shell/shell.h

disable qmlcache temporarily.
Issue: https://github.com/linuxdeepin/developer-center/issues/8289

fix: crashed by qmlcache

---

panels/dock/tray/plugins/bluetooth/bluetoothmainwidget.cpp
panels/dock/tray/plugins/dde-network-core/dock-network-plugin/quickpanel.cpp
panels/dock/tray/widgets/slidercontainer.cpp

set child widget has no focus policy.
Log: fix quick panel popup has focus
Influence: quick panel popup has no focus

fix: quick panel popup has focus

---

panels/dock/tray/frame/window/quickpluginwindow.cpp
panels/dock/tray/frame/window/tray/tray_delegate.cpp

fix: modify plugin hover style

---

panels/dock/workspaceitem/CMakeLists.txt
panels/dock/workspaceitem/package/workspaceitem.qml
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_az.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_bo.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_ca.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_es.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_fi.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_fr.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_hu.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_it.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_ja.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_ko.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_nb_NO.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_pl.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_pt_BR.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_ru.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_uk.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_zh_CN.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_zh_HK.ts
panels/dock/workspaceitem/translations/org.deepin.ds.dock.workspaceitem_zh_TW.ts
panels/dock/workspaceitem/xworkspaceworker.cpp

1. adjust workspace hover aera
2. make x11 workspace name hardcode localize name
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8223
issue: https://github.com/linuxdeepin/developer-center/issues/8278

fix: workspace not localize

---

panels/dock/tray/frame/item/pluginsitem.cpp
panels/dock/tray/frame/window/tray/widgets/systempluginitem.cpp
panels/dock/tray/plugins/airplane-mode/airplanemodeapplet.cpp
panels/dock/tray/plugins/bluetooth/componments/bluetoothadapteritem.cpp
panels/dock/tray/plugins/bluetooth/componments/bluetoothapplet.cpp
panels/dock/tray/plugins/display/brightnessadjwidget.cpp

as title
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7704

fix: some widget layout margin incorrect

---

panels/dock/tray/frame/window/tray/widgets/xembedtrayitemwidget.cpp

as title
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8280

chore: update icon such as weixin(wine)

---

panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/desktopfileabstractparser.cpp

fix: dock crash when get currenActiveWindow is Null

---

shell/main.cpp

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/8211

refact: using dtk's blur

---

debian/changelog

bump version 0.0.15
log: as title

chore: bump version 0.0.15

---

panels/dock/dockdbusproxy.cpp

chore: using Panel to find children applet

---

applets/dde-appearance/appearanceapplet.cpp

QDBusServiceWatcher is invalid.
Issue: https://github.com/linuxdeepin/developer-center/issues/8250

fix: opacity can't flow changed with dde-appearance

---

panels/dock/tray/frame/window/tray/dbustraymanager.cpp
panels/dock/tray/plugins/power/dbus/dbusaccount.cpp
panels/dock/tray/plugins/power/dbus/dbuspower.cpp
panels/dock/tray/plugins/shutdown/dbus/dbusaccount.cpp

fix: dbus warning when exit

---

shell/main.cpp
shell/shell.cpp
shell/shell.h

chore: set QT_QUICK_FLICKABLE_WHEEL_DECELERATION env

---

panels/dock/tray/frame/window/quickpluginwindow.cpp
panels/dock/tray/plugins/uos-ai/uosaiplugin.cpp

fix the problem of abnormal location of uos-ai plugin.
Log: fix the problem of abnormal location of uos-ai plugin
issue: https://github.com/linuxdeepin/developer-center/issues/8322
Influence: uos-ai plugin display

fix: fix the problem of abnormal location of uos-ai plugin

---

frame/pluginloader.cpp
frame/pluginloader.h
shell/main.cpp

It's useful to release Applets early.

feat: destroy plugins manually

---

panels/dock/package/main.qml

log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8353

fix: dock not in left when no left plugins

---

debian/changelog

chore: bump version to 0.0.16

---

panels/dock/tray/frame/quickproxywidget.cpp
panels/dock/tray/frame/window/quickpluginwindow.cpp

事件转发错误，导致后续事件始终转发至同一对象
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8326

fix: event delivery error

---

panels/dock/tray/plugins/bluetooth/componments/bluetoothapplet.cpp

as title
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8279

fix: refresh when bluetooth panel shown

---

panels/dock/x11dockhelper.cpp

update wake area pos after area created
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8163

fix: dock wake area position not right sometime

---

panels/dock/package/main.qml

when checked set to true will remove Binding
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8478

fix: menu checked status not right

---

panels/dock/package/main.qml

accepted mouse click in dragArea click
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8479

fix: click dragArea can open app

---

debian/changelog

bump version 0.0.17
log: as title

chore: bump version 0.0.17

---

panels/dock/package/main.qml

log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8503

fix: menu can uncheked while double click

---

panels/dock/CMakeLists.txt
panels/dock/dockplugin/plugin/CMakeLists.txt

Log: fix some headers can not be found

fix: need link xcb-aux and xkbcommon

---

debian/changelog

bump version 0.0.18
log: as title

chore: bump version 0.0.18

---

debian/changelog

bump version 0.0.22
log: as title

chore: bump version 0.0.22

---

CMakeLists.txt
shell/CMakeLists.txt
shell/main.cpp

chore: add version for dde-shell

---

panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/BeatAnimation.qml
panels/dock/taskmanager/package/LaunchAnimation.qml

Adjust the attention animation with the app launch animation.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8614

fix: The app launch animation exceeds the boundaries.

---

example/layershell-example/main.qml
frame/layershell/dlayershellwindow.h
frame/layershell/qwaylandlayershellsurface.cpp
frame/layershell/x11dlayershellemulation.cpp

feat: add multi screen support

---

panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/appitem.h
panels/dock/taskmanager/x11preview.cpp
panels/dock/taskmanager/x11preview.h
panels/dock/taskmanager/x11utils.cpp

Cancel icon scaling when obtaining icons
Issue: https://github.com/linuxdeepin/developer-center/issues/8649

fix: blurred icons during app preview

---

panels/dock/taskmanager/x11preview.cpp

fix x11 preview display problem
Log: fix x11 preview display problem
Influence: x11 preview display

fix: x11 preview display problem

---

panels/dock/DockPalette.qml
panels/dock/package/main.qml
shell/main.cpp

chore: remove warning

---

example/containment-example/package/main.qml
frame/containment.cpp
frame/pluginloader.cpp
shell/CMakeLists.txt
shell/SceneWindow.qml
shell/dde-shell.qrc
shell/main.cpp

Create an Window for appletItems if non window.

feat: support to display non window plugin

---

panels/dock/taskmanager/package/TaskManager.qml
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h

支持从启动器自由排序区域拖拽应用到任务栏以固定应用。
Log:

feat: drop item to dock to pin app

---

panels/dock/taskmanager/package/WindowIndicator.qml

Issues: linuxdeepin/developer-center#8804

fix(taskmanager): radius of the indicators are not working

---

panels/dock/dockplugin/loader/CMakeLists.txt
panels/dock/dockplugin/plugin/CMakeLists.txt

Log: allow build dockplugin without dde-shell

feat: allow build dockplugin as toplevel project

---

panels/dock/DockCompositor.qml
panels/dock/constants.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h
panels/dock/dockplugin/plugin/plugin.cpp
panels/dock/dockplugin/plugin/plugin.h
panels/dock/dockplugin/plugin/pluginmanager.cpp
panels/dock/dockplugin/plugin/pluginmanager_p.h
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/plugin/pluginsurface_p.h
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h
panels/dock/tray/package/tray.qml

modify plugin-manager xml content
implement loader and compositor function
Log: as title

feat: complete using wayland compositor to load old plugin

---

debian/dde-shell.install
panels/dock/dockplugin/loader/CMakeLists.txt
panels/dock/dockplugin/loader/configs/com.deepin.dde.control-center.gschema.xml
panels/dock/dockplugin/loader/configs/org.deepin.dde.dock.plugin.common.json
panels/dock/dockplugin/loader/interfaces/common.h
panels/dock/dockplugin/loader/interfaces/constants.h
panels/dock/dockplugin/loader/interfaces/pluginproxyinterface.h
panels/dock/dockplugin/loader/interfaces/pluginsiteminterface.h
panels/dock/dockplugin/loader/interfaces/pluginsiteminterface_v2.h
panels/dock/dockplugin/loader/main.cpp
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h

compatible with 1070 plugins for loading them
Log:

chore: compatible with 1070 plugins

---

panels/dock/dockpanel.cpp
panels/dock/dockpanel.h
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h
panels/dock/dockplugin/plugin/pluginmanager.cpp
panels/dock/pluginmanagerextension.cpp

modify loader to load old plugin
Log: as title

feat: can load old plugin

---

panels/dock/DockCompositor.qml
panels/dock/constants.h
panels/dock/dockpanel.cpp
panels/dock/dockpanel.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/plugin/plugin.h

use TRAY_DEBUG_PLUGIN_PATH env for debugging
modify dock compositor
Log: as title

feat: complete loading old plugin

---

debian/dde-shell.install
panels/dock/dockplugin/loader/interfaces/common.h
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h

chore: clean code of loader

---

panels/dock/constants.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/plugin/plugin.h

TrayPopupTypeEmbed
Log: as title

feat: add embed popup type for quick panel

---

panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h

before plugin return panel popup, the popup had called show function
Log: as title

fix: some 1070 tray plugin panel popup not show

---

panels/dock/DockCompositor.qml
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

feat: add pluginId and itemKey info for popup surface

---

panels/dock/dockplugin/loader/widgetplugin.cpp

fix: embed panel popup not show

---

panels/dock/pluginmanagerextension_p.h

fix: popup surface can close

---

panels/dock/dockplugin/loader/interfaces/common.h
panels/dock/dockplugin/loader/widgetplugin.cpp

modify the condition that check tray and quick flags
Log:

fix: don't display sound tray

---

frame/qml/PanelPopupWindow.qml

chore: set ColorSelector's family for popup

---

frame/qml/PanelPopup.qml
panels/dock/tray/package/tray.qml

chore: add check for tray when PopupCreated

---

frame/qml/PanelPopup.qml
panels/dock/tray/package/tray.qml

fix: adjust PopupWindow's position

---

panels/dock/taskmanager/x11preview.cpp
panels/dock/taskmanager/x11preview.h

Restrict the size of preview containers
Issue: https://github.com/linuxdeepin/developer-center/issues/8801

fix: Application preview UI issue

---

panels/dock/package/main.qml

fix: plugin color theme does not change

---

panels/dock/tray/CMakeLists.txt
panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/CMakeLists.txt
panels/dock/tray/quickpanel/DragItem.qml
panels/dock/tray/quickpanel/PanelPluginPage.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/PluginItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml
panels/dock/tray/quickpanel/QuickPanelModel.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml
panels/dock/tray/quickpanel/SubPluginPage.qml
panels/dock/tray/quickpanel/quickpanelproxymodel.cpp
panels/dock/tray/quickpanel/quickpanelproxymodel.h

feat: add quickpanel for tray

---

panels/dock/dockplugin/loader/main.cpp
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h

get the object by pluginLoader's instance()
Log:

fix: fail to convert PluginsItemInterface to qobject

---

panels/dock/tray/quickpanel/CMakeLists.txt
panels/dock/tray/quickpanel/PluginItem.qml
panels/dock/tray/quickpanel/ShellSurfaceItemProxy.qml
panels/dock/tray/quickpanel/SubPluginPage.qml

Update client's size when change SurfaceItem's size.

fix: incorrect size for SurfaceItem

---

panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h
panels/dock/dockplugin/plugin/plugin.h
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/plugin/pluginsurface_p.h
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

The popup can set the size sent from the compositor
Log: as title

feat: popup can set the size sent from compositor

---

panels/dock/dockplugin/loader/widgetplugin.cpp

set background color of applet widget to WA_TranslucentBackground
Log:

fix: wrong background color

---

panels/dock/CMakeLists.txt
panels/dock/dconfig/org.deepin.ds.dock.tray.json
panels/dock/tray/quickpanel/quickpanelproxymodel.cpp
panels/dock/tray/quickpanel/quickpanelproxymodel.h

adjust order.
rename proxyModel's function.

feat: add order for quickpanel

---

panels/dock/dockplugin/plugin/plugin.cpp
panels/dock/dockplugin/plugin/plugin.h
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

add popup level, e.g., PopupFirst, PopupSecond
Log:

feat: add popup level

---

panels/dock/tray/quickpanel/DragItem.qml
panels/dock/tray/quickpanel/PanelPluginPage.qml
panels/dock/tray/quickpanel/PluginItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml
panels/dock/tray/quickpanel/QuickPanelModel.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml
panels/dock/tray/quickpanel/SubPluginPage.qml
panels/dock/tray/quickpanel/quickpanelproxymodel.cpp
panels/dock/tray/quickpanel/quickpanelproxymodel.h

fix: adjust drag for quickpanel

---

panels/dock/tray/package/ActionShowStashDelegate.qml

fix: use Panel.position in ActionShowStashDelegate

---

panels/dock/constants.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/plugin/plugin.cpp
panels/dock/dockplugin/plugin/plugin.h
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

Synchronize the sizePolicy attribute through the protocol
Log: as title

feat: plugin add sizePolicy property

---

panels/dock/dockplugin/loader/interfaces/common.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h
panels/dock/dockplugin/plugin/plugin.cpp
panels/dock/dockplugin/plugin/plugin.h

feat: set message callback function to v2-plugin

---

panels/dock/dockplugin/plugin/plugin.cpp
panels/dock/dockplugin/plugin/plugin.h
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

revert the commit that add the popuplayer
Log:

chore: revert the popuplayer commit

---

frame/qml/PanelPopup.qml
frame/qml/PanelToolTip.qml
panels/dock/tray/package/tray.qml

Display tooltip by PanelToolTip instead of PanelPopup.

feat: support to change contentItem for PanelToolTip

---

panels/dock/constants.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

feat: add setAppletMinHeight interface for v2-plugin

---

LICENSES/LGPL-2.0-or-later.txt
frame/qml/PanelPopup.qml
panels/dock/tray/CMakeLists.txt
panels/dock/tray/ksortfilterproxymodel.cpp
panels/dock/tray/ksortfilterproxymodel.h
panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/package/ActionShowStashDelegate.qml
panels/dock/tray/package/ActionToggleCollapseDelegate.qml
panels/dock/tray/package/DummyDelegate.qml
panels/dock/tray/package/StashContainer.qml
panels/dock/tray/package/StashedItemDelegateChooser.qml
panels/dock/tray/package/StashedItemPositioner.qml
panels/dock/tray/package/TrayItemPositioner.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/traysortordermodel.cpp
panels/dock/tray/traysortordermodel.h

初步支持可隐藏区域的托盘
Log:
-----------
由于尚不支持拖拽，所以目前是在调试模式（`QT_DEBUG` 被定义时）下，`trash::trash` 和 `dnd-mode::dnd-mode-key` 会收到托盘里。

feat: initial layout for stashed tray layout

---

panels/dock/dockplugin/loader/CMakeLists.txt
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/quickpluginitem.cpp
panels/dock/dockplugin/loader/quickpluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp

fix: contextMenu and tooltip can't show in quick panel

---

panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/widgetplugin.cpp

feat: loader support setting appletContainer property

---

panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml
panels/dock/tray/quickpanel/quickpanelproxymodel.cpp
panels/dock/tray/quickpanel/quickpanelproxymodel.h

as title.
TODO: reposition popup

feat: distinguish the pop-up types between quick and tray

---

panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

fix: server pluginManager cannot send event msg

---

frame/qml/PanelPopup.qml
panels/dock/tray/quickpanel/PanelPluginPage.qml
panels/dock/tray/quickpanel/PluginItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml
panels/dock/tray/quickpanel/SubPluginPage.qml

fix: adjust quickpanel's style

---

panels/dock/dockplugin/loader/interfaces/constants.h
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/quickpluginitem.cpp
panels/dock/dockplugin/loader/quickpluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h

feat: add quick item menu

---

panels/dock/dockplugin/loader/widgetplugin.cpp

fix: correctly initialize the fixed area plugin

---

panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/quickpluginitem.cpp
panels/dock/dockplugin/loader/quickpluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp

fix: plugin displays two tooltips

---

panels/dock/tray/quickpanel/QuickPanelPage.qml

feat: add menu for quickpanel

---

panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/plugin/plugin.cpp
panels/dock/dockplugin/plugin/plugin.h
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

fix: add plugin display name property

---

panels/dock/tray/quickpanel/quickpanelproxymodel.cpp

fix: get incorrect property for quickpanel's title

---

frame/qml/PanelPopupWindow.qml
panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/tray/quickpanel/PanelPluginPage.qml
panels/dock/tray/quickpanel/PluginItem.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml
panels/dock/tray/quickpanel/ShellSurfaceItemProxy.qml

removing warning.
nullptr check for Popup.

fix: popup's position for quickpanel

---

panels/dock/tray/quickpanel/DragItem.qml
panels/dock/tray/quickpanel/PanelPluginPage.qml
panels/dock/tray/quickpanel/PluginItem.qml

feat: add drag from quickpanel to tray

---

panels/dock/tray/quickpanel/QuickPanelPage.qml
panels/dock/tray/quickpanel/SubPluginPage.qml

fix: incorrect width for quickpanel's subpage.

---

frame/layershell/x11dlayershellemulation.cpp
panels/dock/dockpanel.cpp
panels/dock/dockpanel.h
panels/dock/docksettings.cpp
panels/dock/package/main.qml
panels/dock/x11dockhelper.cpp
panels/dock/x11dockhelper.h

Re-implement the dock processing flow on the X11
Log:

feat: Re-implement the dock processing flow on the X11

---

debian/control

fix: missing package

---

panels/dock/dconfig/org.deepin.ds.dock.tray.json
panels/dock/tray/CMakeLists.txt
panels/dock/tray/traysortordermodel.cpp
panels/dock/tray/traysortordermodel.h

chore: store/load tray state data from DConfig

---

panels/dock/package/main.qml

adjust Inner border and outer border
Issue: https://github.com/linuxdeepin/developer-center/issues/8342

fix: dock panel border color issue

---

panels/dock/tray/plugins/uos-ai/uosaiplugin.cpp

use uosai.svg instead of UosAiAssistant
Issue: https://github.com/linuxdeepin/developer-center/issues/9363

fix: uos-ai icon error

---

panels/dock/dockplugin/loader/pluginitem.cpp
panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/quickpluginitem.cpp
panels/dock/dockplugin/loader/quickpluginitem.h
panels/dock/tray/quickpanel/QuickPanelPage.qml

popup's (x, y) is window's topLeft aligning with emit position.

fix: adjust popup's position

---

shell/main.cpp

fix(build): QIcon header missing

---

frame/qml/PanelPopup.qml
frame/qml/PanelToolTip.qml
panels/dock/tray/package/ActionShowStashDelegate.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/PanelPluginPage.qml
panels/dock/tray/quickpanel/QuickPanel.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml

using Binding to control when enable binding.
offset is controlled by caller.

fix: adjust position of popup and tooltip

---

panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

feat: add plugin surface size property and sizeChanged signal

---

panels/dock/tray/quickpanel/PluginItem.qml

feat: get fallbackIconSize from shellSurface

---

panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h
panels/dock/dockplugin/plugin/pluginsurface.cpp

feat: can set plugin dock panel size

---

panels/dock/dockplugin/loader/CMakeLists.txt
panels/dock/dockplugin/loader/loader.qrc
panels/dock/dockplugin/loader/texts/plugin_item_disconnect_16px.svg
panels/dock/dockplugin/loader/texts/plugin_item_select_16px.svg

feat: add loader plugin_item_select svg res

---

panels/dock/dockplugin/loader/main.cpp
panels/dock/dockplugin/loader/quickpluginitem.cpp
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/loader/widgetplugin.h
panels/dock/dockplugin/plugin/plugin.cpp
panels/dock/dockplugin/plugin/plugin.h

adjust itemAdded and itemRemoved function;
Log: as title

fix: plugin can be hidden and then shown normally

---

panels/dock/dockplugin/loader/pluginitem.cpp

fix: adjust tray item widget size

---

frame/qml/PanelPopup.qml
frame/qml/PanelPopupWindow.qml

other PanelPopup doesn't close

fix: more than one popups

---

frame/ddeshell_qml.qrc
frame/panel.cpp
frame/plugin/qmlplugin.cpp
frame/qml/PanelPopupWindow.qml
frame/qml/PanelToolTipWindow.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml

popup's radius is following with system's radius.

feat: separate popup and tooltip's window

---

panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/TaskManager.qml

DelegateModel 数据和 model 中数据没有同步。
现在就算在其他区域松开也是会更新到 model
Issue: https://github.com/linuxdeepin/developer-center/issues/9345

fix: dock item duplicated after drag and drop

---

panels/dock/tray/quickpanel/DragItem.qml
panels/dock/tray/quickpanel/PanelPluginPage.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/PluginItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml
panels/dock/tray/quickpanel/SubPluginPage.qml

status of item in tray follows popup's visibility. add blur for drag's window
adjust button's color.

fix: adjust style for quickpanel

---

.reuse/dep5

chore: license reuse

---

panels/dock/dockplugin/loader/pluginitem.h
panels/dock/dockplugin/loader/quickpluginitem.cpp
panels/dock/dockplugin/loader/quickpluginitem.h
panels/dock/dockplugin/loader/widgetplugin.cpp
panels/dock/dockplugin/plugin/plugin.h
panels/dock/dockplugin/plugin/pluginsurface.cpp
panels/dock/dockplugin/protocol/plugin-manager-v1.xml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

feat: send plugin item widget's mouse press event to server

---

panels/dock/tray/quickpanel/DragItem.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/PluginItem.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml
panels/dock/tray/quickpanel/ShellSurfaceItemProxy.qml
panels/dock/tray/quickpanel/SubPluginPage.qml

chore: using Proxy for ShellSurfaceItem

---

frame/dsqmlglobal.cpp
frame/panel.cpp
frame/private/dsqmlglobal_p.h
frame/private/panel_p.h
frame/qml/PanelPopupWindow.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml

close children window when it close.
close tooltip window when popup is shown.

feat: manage opened window

---

panels/dock/tray/quickpanel/DragItem.qml
panels/dock/tray/quickpanel/PluginItem.qml

Drag need disabled if plugin acceptes MousePress, and it relay on dde-tray-loader's change.

fix: drag conficts with plugin

---

panels/dock/taskmanager/x11preview.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/8736

fix: window can not be actived from preview window

---

frame/qml/PanelPopup.qml
frame/qml/PanelToolTip.qml

Order x after width when Binding works.

fix: popup outside the screen

---

panels/dock/tray/quickpanel/PanelTrayItem.qml

fix: PanelTrayItem get a unexcepted size

---

panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h
panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml

feat: implement set_position protocal for server

---

debian/changelog
panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/TaskManager.qml
panels/dock/taskmanager/x11preview.cpp
panels/dock/workspaceitem/package/workspaceitem.qml

Fix：
- https://github.com/linuxdeepin/developer-center/issues/7984
- https://github.com/linuxdeepin/developer-center/issues/8942
- https://github.com/linuxdeepin/developer-center/issues/9345
- https://github.com/linuxdeepin/developer-center/issues/8630

bump version to 0.0.26 

---

panels/dock/tray/package/ActionToggleQuickSettingsDelegate.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml
panels/dock/tray/quickpanel/quickpanelproxymodel.cpp
panels/dock/tray/quickpanel/quickpanelproxymodel.h

chore: move quickpanel to tray container

---

panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/QuickPanelPage.qml

fix: update popup's position in quickpanel

---

debian/control

as title
Log: as title
Influence: dde-shell running

chore: modify running depends

---

panels/dock/dockpanel.cpp
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h
panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml

feat: add rawGlobalPos for client get pos in xrog

---

panels/dock/pluginmanagerextension.cpp
panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml

move geometry's check from server to client.

fix: tooltip's leftTop position is (0, 0)

---

frame/qml/PanelPopupWindow.qml

fix: popup can not get input focus

---

panels/dock/tray/package/tray.qml

调整应用托盘所位于的默认区域，应用托盘默认位于托盘区域，其它插件默
认位于折叠区域。
Log:

chore: adjust application tray default area

---

panels/dock/dockpanel.cpp

init hidestate from right state
log: as title

fix: dock now show when init

---

frame/qml/PanelPopupWindow.qml
panels/dock/CMakeLists.txt
panels/dock/clipboarditem/package/clipboarditem.qml
panels/dock/dockpositioner.cpp
panels/dock/dockpositioner.h
panels/dock/launcherItem/package/launcheritem.qml
panels/dock/multitaskview/package/multitaskview.qml
panels/dock/searchitem/package/searchitem.qml
panels/dock/taskmanager/package/AppItem.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml

add DockPanelPositioner to align with dock.

feat: support popup to align with dock

---

panels/dock/DockPalette.qml
panels/dock/clipboarditem/clipboarditem.cpp
panels/dock/clipboarditem/clipboarditem.h
panels/dock/clipboarditem/package/clipboarditem.qml

as title
Log: as title
Influence: clipboard item active status

feat: add clipboard plugin item active when clipboard is visible

---

panels/dock/searchitem/package/searchitem.qml
panels/dock/searchitem/searchitem.cpp
panels/dock/searchitem/searchitem.h

as title
Log: as title
Influence: grandSearch item active status

feat: add grandSearch plugin item active when clipboard is visible

---

panels/dock/DockCompositor.qml

fix: findSurface should find from all models

---

frame/quick/dsquickdrag.cpp

fix: crashed when using DQuickDrag second

---

panels/dock/DockCompositor.qml
panels/dock/tray/package/tray.qml

quickPlugin is not display in tray.

fix: incorrect popup's filter in tray

---

panels/dock/taskmanager/package/AppItem.qml

Dynamically resize the window indicator margin size
Issue: https://github.com/linuxdeepin/developer-center/issues/9577

fix: window indicator margin

---

panels/dock/tray/package/ActionShowStashDelegate.qml

feat: add rotation animation when open stashdelegate

---

panels/dock/tray/package/ActionToggleQuickSettingsDelegate.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/9624

feat: support dock's layout for quickpanel

---

frame/panel.cpp
frame/private/panel_p.h

Remove the feature for panelpopup.

fix: tooltip and popup can't be displayed together

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml

支持 isItemActive 托盘插件属性（但是目前似乎没有插件用了这个属性）
Log:

feat: support isItemActive property for tray plugins

---

panels/dock/DockCompositor.qml
panels/dock/tray/ShellSurfaceItemProxy.qml
panels/dock/tray/package/ActionToggleQuickSettingsDelegate.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/QuickPanel.qml

- fix: client's surface maybe invalid
- fix: popup and tooltip is displayed together for quickpanel

panelpopup

---

panels/dock/OverflowContainer.qml
panels/dock/package/main.qml
panels/dock/tray/package/tray.qml

fix: tray shake when playing animation

---

panels/dock/package/main.qml

Indent the border by 0.5px
Adjust outer border transparency
Issue: https://github.com/linuxdeepin/developer-center/issues/8342

fix: The border may disappear when dragging

---

debian/changelog
panels/dock/dockpanel.cpp
panels/dock/taskmanager/package/AppItem.qml

chore: bump version to 0.0.28

---

panels/dock/workspaceitem/package/workspaceitem.qml

fix: incorrect position of workspace

---

panels/dock/tray/trayitem.cpp
panels/dock/tray/trayitem.h

This reverts commit 57544a2209d605367b01c2f36c2d26b5bf344e96.
Issue: https://github.com/linuxdeepin/developer-center/issues/9714
Issue: https://github.com/linuxdeepin/developer-center/issues/9718

Revert "fix: dock or undock abnormal function (#546)"

---

archlinux/PKGBUILD
frame/qml/PanelToolTip.qml

fix: set invalid xdg-surface geometry on wayland

---

panels/dock/package/main.qml

fix: popup doesn't close when dock changes position

---

panels/dock/tray/package/ActionShowStashDelegate.qml

Popup stash based on dock position
Issue: https://github.com/linuxdeepin/developer-center/issues/9739
Issue: https://github.com/linuxdeepin/developer-center/issues/9725

fix: stash popup location

---

panels/dock/x11dockhelper.cpp

Trigger area need to map native geometry in x11.

fix: incorrect trigger area when scaling

---

frame/qml/PanelToolTipWindow.qml

add flag to stay on top.
Issue: https://github.com/linuxdeepin/developer-center/issues/9779

fix: tooltip is hide

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml

Add item beyond dock range judgment
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/9769

fix: Time zone overlaps with dock

---

debian/control
frame/CMakeLists.txt
frame/dsqmlglobal.cpp
frame/dsutility.cpp
frame/dsutility.h
frame/private/dsqmlglobal_p.h
frame/private/utility_x11_p.h
frame/utility_x11.cpp

when click outside, the window will be closed.

feat: add grabMouse for window

---

.gitignore
panels/dock/tray/CMakeLists.txt
panels/dock/tray/translations/org.deepin.ds.dock.tray.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_az.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_bo.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ca.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_en.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_es.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_fi.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_fr.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_hu.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_it.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ja.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ko.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_nb_NO.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_pl.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_pt_BR.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ru.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_uk.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_zh_CN.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_zh_HK.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_zh_TW.ts

Issue: linuxdeepin/developer-center#9671

fix: Update taskbar plugin translation

---

panels/dock/tray/package/tray.qml
panels/dock/tray/trayitem.cpp
panels/dock/tray/trayitem.h

时间日期插件属于 fixed 插件
Issues: linuxdeepin/developer-center#9820

fix: Unable to set whether the datetime plugin is visible

---

frame/utility_x11.cpp

fix: menu item can't work

---

debian/changelog

chore: bump version to 0.0.29

---

frame/qml/PanelPopupWindow.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/9896

fix: popup can drag

---

panels/dock/workspaceitem/package/workspaceitem.qml

workSpace toolTip text error
Issue: https://github.com/linuxdeepin/developer-center/issues/9877

fix: workSpace toolTip text error

---

panels/dock/tray/package/ActionShowStashDelegate.qml

Just icon rotation
log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9880

fix: Tray button rotates as a whole

---

panels/dock/taskmanager/x11preview.cpp

Background Alignment Preview Image
Issue: https://github.com/linuxdeepin/developer-center/issues/9433

fix: Application preview background color overflow

---

panels/dock/tray/quickpanel/PanelTrayItem.qml

fix: Quick panel size error without sound plugin

---

frame/qml/PanelMenu.qml
frame/qml/PanelPopup.qml

using Item's width for Popup's width.

refact: using Item instead of Popup for PanelPopup

---

panels/dock/tray/SurfacePopup.qml

using DockPositioner to update menu's position.
Issue: https://github.com/linuxdeepin/developer-center/issues/9899

fix: incorrect position for stash's menu

---

debian/changelog

chore: bump version to 0.0.30

---

panels/dock/DockCompositor.qml
panels/dock/package/main.qml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h

feat: update plugin's dockSize

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml

update tray raw global pos
log: as title

fix: unable to click x tray

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/package/ActionShowStashDelegate.qml
panels/dock/tray/package/StashContainer.qml
panels/dock/tray/package/TrayContainer.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/traysortordermodel.cpp

托盘增加拖拽时候的挤动效果
可以通过将item拖向stashItem实现拖入应用托盘
Log: Drag the tray to increase the squeezing effect

feat: Drag the tray to increase the squeezing effect

---

panels/dock/tray/quickpanel/PluginItem.qml

fix: adjust palette for quickpanel

---

debian/changelog

release version 0.0.31
Log: release version 0.0.31

chore: bump version to 0.0.31

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/package/ActionShowStashDelegate.qml
panels/dock/tray/package/StashContainer.qml
panels/dock/tray/package/TrayContainer.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/traysortordermodel.cpp

This reverts commit 67d6e8b9300d1eec8ba1052b5b564e629adfcdba.
Reason: MouseArea causes plugin icon to be unable to click

Revert "feat: Drag the tray to increase the squeezing effect"

---

panels/dock/dockdbusproxy.cpp
panels/dock/dockdbusproxy.h
panels/dock/showdesktop/CMakeLists.txt
panels/dock/showdesktop/package/icons/showdesktop.svg
panels/dock/showdesktop/showdesktop.cpp
panels/dock/showdesktop/showdesktop.h
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_az.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_bo.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ca.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_es.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_fi.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_fr.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_hu.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_it.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ja.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ko.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_nb_NO.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_pl.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_pt_BR.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ru.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_uk.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_zh_CN.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_zh_HK.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_zh_TW.ts

Issues: linuxdeepin/developer-center#9820

fix: unable to set visibility of 'Show Desktop' in DCC

---

debian/changelog

bump version to 0.0.32
Log: bump version to 0.0.32

chore: bump versiont to 0.0.32

---

panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_az.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_bo.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ca.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_es.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_fi.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_fr.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_hu.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_it.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ja.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ko.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_nb_NO.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_pl.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_pt_BR.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_ru.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_uk.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_zh_CN.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_zh_HK.ts
panels/dock/showdesktop/translations/org.deepin.ds.dock.showdesktop_zh_TW.ts

add show-desktop tooltips translation
Log: add show-desktop tooltips translation

chore: add show-desktop tooltips translation

---

panels/dock/clipboarditem/translations/org.deepin.ds.dock.clipboarditem_zh_CN.ts
panels/dock/clipboarditem/translations/org.deepin.ds.dock.clipboarditem_zh_HK.ts
panels/dock/clipboarditem/translations/org.deepin.ds.dock.clipboarditem_zh_TW.ts

issue: https://github.com/linuxdeepin/developer-center/issues/9965

fix: Update translation

---

panels/dock/AppletItemBackground.qml
panels/dock/AppletItemButton.qml
panels/dock/CMakeLists.txt
panels/dock/clipboarditem/package/clipboarditem.qml
panels/dock/searchitem/package/searchitem.qml
panels/dock/showdesktop/package/showdesktop.qml
panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/package/ActionShowStashDelegate.qml
panels/dock/tray/package/ActionToggleCollapseDelegate.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml

using AppletItemBackground for Applet's background,
using AppletItemButton for normal applet
Issue: https://github.com/linuxdeepin/developer-center/issues/8633

fix: adjust ui for dock's applet

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/package/TrayItemDelegateChooser.qml

chore: disable fixed plugins dragging

---

applets/dde-appearance/org.deepin.dde.Appearance1.xml

chore: appearance 添加GlobalTheme属性

---

panels/dock/dockpanel.cpp
panels/dock/dockpositioner.cpp
panels/dock/dockpositioner.h
panels/dock/tray/package/StashContainer.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/trayitempositionmanager.cpp

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/9995
Issue: https://github.com/linuxdeepin/developer-center/issues/9894

fix: adjust ui

---

panels/dock/tray/package/StashContainer.qml
panels/dock/tray/package/TrayContainer.qml

Plugin should not be dragged into the application tray, Only allow apps to be dragged into the app tray
Issue: https://github.com/linuxdeepin/developer-center/issues/10048

fix: Plugin should not be dragged into the application tray

---

panels/dock/tray/SurfacePopup.qml
panels/dock/tray/package/StashContainer.qml
panels/dock/tray/package/StashedItemDelegateChooser.qml

Menu is aligned with topLeft.
tooltip need to restore surface's position to topLeft position

fix: incorrect position for tooltip and menu in second popup

---

panels/dock/dockhelper.h
panels/dock/dockpanel.cpp
panels/dock/docksettings.cpp
panels/dock/package/main.qml
panels/dock/waylanddockhelper.cpp
panels/dock/waylanddockhelper.h
panels/dock/x11dockhelper.cpp
panels/dock/x11dockhelper.h

Add smart hide function
Issue: https://github.com/linuxdeepin/developer-center/issues/9842

feat: Add smart hide function

---

panels/dock/dconfig/org.deepin.ds.dock.tray.json
panels/dock/tray/traysortordermodel.cpp

* 修改配置文件，设置顺序
* 新图标使用 prepend 放置在前方
Issues: linuxdeepin/developer-center#10049

chore: modify the order of systray

---

panels/dock/tray/translations/org.deepin.ds.dock.tray.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_az.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_bo.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ca.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_en.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_es.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_fi.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_fr.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_hu.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_it.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ja.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ko.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_nb_NO.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_pl.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_pt_BR.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_ru.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_uk.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_zh_CN.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_zh_HK.ts
panels/dock/tray/translations/org.deepin.ds.dock.tray_zh_TW.ts

Update tray translation
Log: Update tray translation

chore: Update tray translation

---

panels/dock/tray/package/ActionShowStashDelegate.qml
panels/dock/tray/package/ActionToggleCollapseDelegate.qml

add tooltip
Issue: https://github.com/linuxdeepin/developer-center/issues/10031

fix:application tray and collapse tray dose not have tooltip

---

debian/changelog

bump version 0.0.33
Log: bump version 0.0.33

chore: bump version 0.0.33

---

frame/qml/PanelPopup.qml
frame/qml/PanelToolTip.qml

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10119
Influence: tooltip and panle popup display

chore: tooltip poupu and panel popup delayed show

---

panels/dock/x11dockhelper.cpp
panels/dock/x11dockhelper.h

Setting the dock to above state
Issue: https://github.com/linuxdeepin/developer-center/issues/9996
Issue: https://github.com/linuxdeepin/developer-center/issues/9992

fix: dock needs to be on top of the launchpad

---

panels/dock/tray/quickpanel/PluginItem.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/9798

fix: adjust border's width for quickpanel

---

panels/dock/tray/package/StashContainer.qml
panels/dock/tray/package/StashedItemDelegateChooser.qml
panels/dock/tray/package/StashedItemPositioner.qml

adjust spacing for items.
adjust stashed's background.
Issue: https://github.com/linuxdeepin/developer-center/issues/9894

fix: adjust ui for stashed

---

panels/dock/launcherItem/package/launcheritem.qml

Set the screen of the dock to the screen of the fullscreen frame
Issue: https://github.com/linuxdeepin/developer-center/issues/7188

fix: fullscreen frame follows the dock

---

panels/dock/OverflowContainer.qml

多计算了 spacing
Issues: linuxdeepin/developer-center#10077

fix: wrong size

---

frame/dsqmlglobal.cpp
frame/dsutility.cpp
frame/dsutility.h
frame/panel.cpp
frame/private/utility_x11_p.h
frame/qml/PanelMenuWindow.qml
frame/utility_x11.cpp
panels/dock/tray/SurfaceSubPopup.qml
panels/dock/tray/TrayItemSurfacePopup.qml

Select a child menu window to grab when leave main menu.
child menu window ungrab and regrab main window when leaved.
Close all window when press outside.

fix: sub menu miss focus

---

panels/dock/tray/package/StashedItemDelegateChooser.qml

fix: adjust radius for stashed

---

panels/dock/tray/package/ActionToggleCollapseDelegate.qml

correct icon direction
log: as title

fix: icon direction

---

frame/quick/dsquickdrag.cpp
frame/quick/dsquickdrag_p.h
panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/quickpanel/DragItem.qml

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/9819
Influence: dragging plugin and plugin item display

fix: drag plugin item cause plugin's event blocked

---

shell/CMakeLists.txt
shell/main.cpp
shell/org.deepin.dde.shell.json
shell/shell.cpp
shell/shell.h

feat: add dconfig migration

---

panels/dock/package/main.qml

chore: make dock transparent in wayland

---

panels/dock/package/main.qml

fix: add scope(layershell namespace) for dock

---

debian/changelog

bump version to 0.0.35
Log: bump version to 0.0.35

chore: bump version to 0.0.35

---

panels/dock/tray/TrayItemSurfacePopup.qml
panels/dock/tray/package/TrayItemDelegateChooser.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/10174

fix: missing active state for tray's popup

---

frame/CMakeLists.txt

fix: Need link x11

---

panels/dock/dockpanel.h
panels/dock/package/main.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/10177

fix: popup doesn't close when dragging

---

frame/private/applet_p.h
frame/private/utility_x11_p.h
frame/qml/PanelMenuWindow.qml
frame/utility_x11.cpp
panels/dock/dockpanel.cpp
panels/dock/dockpanel.h
panels/dock/package/main.qml
panels/dock/tray/SurfaceSubPopup.qml

using DS.grabMouse in dockpanel.
using `mainWindow` to distinguish with NormalWindow.

fix: grabMouse can't ungrab

---

panels/dock/tray/quickpanel/QuickPanel.qml

filter quickpanel's menu.
Issue: https://github.com/linuxdeepin/developer-center/issues/10306

fix: quickpanel hide when right sound

---

debian/changelog

bump version to 0.0.36
Log: bump version to 0.0.36

chore: bump version to 0.0.36

---

shell/main.cpp

由于 kwin 来不及改，暂时回退应用名称的变更。
Log:

fix: temporary revert application name change

---

debian/changelog

bump version to 0.0.37
Log: bump version to 0.0.37

chore: bump version to 0.0.37

---

panels/dock/OverflowContainer.qml
panels/dock/taskmanager/appitem.cpp
panels/dock/taskmanager/itemmodel.cpp
panels/dock/taskmanager/itemmodel.h
panels/dock/taskmanager/package/TaskManager.qml
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h

feat: animation on item add to dock

---

panels/dock/tray/package/ActionToggleCollapseDelegate.qml
panels/dock/tray/package/TrayItemPositioner.qml
panels/dock/tray/traysortordermodel.h

Distinguish between unfolded and contracted animations
Log: pugin drag and drop animation is slow

fix: pugin drag and drop animation is slow

---

debian/changelog

bump version to 0.0.38
Log: bump version to 0.0.38

chore: bump version to 0.0.38

---

panels/dock/taskmanager/CMakeLists.txt
panels/dock/taskmanager/api/wayland-protocols/treeland-foreign-toplevel-manager-v1.xml
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h
panels/dock/taskmanager/treelandwindow.cpp
panels/dock/taskmanager/treelandwindow.h
panels/dock/taskmanager/treelandwindowmonitor.cpp
panels/dock/taskmanager/treelandwindowmonitor.h

rename wayland(treeland special protocols) to treeland
log: as title

feat: add window minimized pos for treeland

---

debian/changelog

bump version to 0.0.39
Log: bump version to 0.0.39

chore: bump version to 0.0.39

---

panels/dock/tray/quickpanel/SubPluginPage.qml

missing to reduce margin of header.
Issue: https://github.com/linuxdeepin/developer-center/issues/10036

fix: incorrect height for quickpanel's childplugin

---

panels/dock/tray/quickpanel/PluginItem.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/10379

fix: incorrect backgroundColor for quickpanel's item

---

panels/dock/tray/trayitem.cpp
panels/dock/tray/trayitem.h

fix: the visibility of the item cannot be set before calling the plugins

---

panels/dock/dconfig/org.deepin.ds.dock.tray.json

Issues: https://pms.uniontech.com/bug-view-258027.html

chore: preset the disk mount plugin to pinned area

---

debian/changelog

bump version to 0.0.40
Log: bump version to 0.0.40

chore: bump version to 0.0.40

---

panels/dock/tray/package/TrayContainer.qml
panels/dock/tray/package/TrayItemPositioner.qml

At the beginning of dragging, do not execute animation
Issue: linuxdeepin/developer-center#10330

fix: incorrect animation application when dragging

---

frame/qml/PanelPopupWindow.qml

feat: make popup transparent on wayland

---

panels/dock/package/main.qml
panels/dock/x11dockhelper.cpp
panels/dock/x11dockhelper.h

Add monitoring dock screen change processing
Issue: https://github.com/linuxdeepin/developer-center/issues/10404

fix: Dock following mouse display error when modifying SmartHide

---

panels/dock/CMakeLists.txt
panels/dock/dockpanel.cpp
panels/dock/dockpanel.h
panels/dock/loadtrayplugins.cpp
panels/dock/loadtrayplugins.h

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10400

fix: plugin process is pulled up again after crashed

---

.reuse/dep5
.tx/transifex.yaml

feat: add transifex config

---

frame/qml/PanelPopupWindow.qml

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10325

fix: modify panel popup shadow offset and color

---

panels/dock/taskmanager/appitem.cpp

Send a signal SIGTERM to the process to terminal the program
Issue: https://github.com/linuxdeepin/developer-center/issues/10436

fix: forced exit is invalid

---

panels/dock/searchitem/package/searchitem.qml

Narrowing the scope to Button
Issue: https://github.com/linuxdeepin/developer-center/issues/10294

fix: searchItem right click response range is too large

---

panels/dock/tray/quickpanel/SubPluginPage.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/9852

chore: adjust iconSize for quickpanel

---

panels/dock/taskmanager/package/TaskManager.qml

fix: animation when drag from launchpad to dock

---

panels/dock/x11dockhelper.cpp
panels/dock/x11dockhelper.h

Unprocessed screen insertion or removal scenarios
Issue: https://github.com/linuxdeepin/developer-center/issues/10205

fix: After modifying the insertion or removal of the screen, the dock following mouse function does not take effect

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/package/ActionToggleCollapseDelegate.qml
panels/dock/tray/package/TrayContainer.qml
panels/dock/tray/package/TrayItemDelegateChooser.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/10357

fix: doesn't disable hover when dragging for tray

---

panels/dock/AppletItemButton.qml
panels/dock/tray/package/ActionToggleCollapseDelegate.qml

add a property to control whether the popup is automatically hidden when clicked
Issue: https://github.com/linuxdeepin/developer-center/issues/9989

fix: can't hide stash popup when AppletItemButton clicked

---

frame/qml/PanelPopupWindow.qml

as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10325

fix: modify panel popup shadow color

---

frame/qml/PanelToolTip.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/10476

fix: tooltip's font can't change flowing setting

---

debian/changelog

chore: bump version to 0.0.43

---

panels/dock/tray/ShellSurfaceItemProxy.qml
panels/dock/tray/quickpanel/PanelTrayItem.qml
panels/dock/tray/quickpanel/PluginItem.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/9799

fix: missing hovered state for quickpanel

---

panels/dock/tray/quickpanel/PanelPluginPage.qml

as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/9803

fix: missing hovered background for quickpanel's power button

---

debian/control
panels/dock/tray/SurfacePopup.qml
panels/dock/tray/SurfaceSubPopup.qml
panels/dock/tray/TrayItemSurfacePopup.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/quickpanel/PanelPluginPage.qml

chore: adjust code style

---

panels/dock/clipboarditem/clipboarditem.cpp

fix: Stuck in dbus data acquisition

---

panels/dock/taskmanager/package/AppItem.qml

fix: Dragging lag caused by animation

---

panels/dock/taskmanager/package/AppItem.qml
panels/dock/taskmanager/package/BeatAnimation.qml
panels/dock/taskmanager/package/TaskManager.qml

Revert "chore: Reimplement notification animation"
reverts commit
- ba28182b249fabda2322ea6523ac066d1bdda39c.
- 2f8de9376b14bc0f7b14b81cc9dd2fdb52828b1a

Revert "fix: Dragging lag caused by animation"

---

debian/changelog

Update translation, prepare branching for release/beige
* fix missing hovered state for quickpanel
(linuxdeepin/developer-center#9799)
* fix missing hovered background for quickpanel's power button
(linuxdeepin/developer-center#9803)
* Modify the taskbar preview close button to a perfect circle
(linuxdeepin/developer-center#9813)
* Revert ripple animation for maintain branch
Log:

chore: release dde-shell 1.0.0

---

panels/dock/clipboarditem/clipboarditem.cpp

This reverts commit 70a2ea31b8f72d2732ff906e7f5ba8be14eaa369.

Revert "fix: Stuck in dbus data acquisition"

---

panels/dock/tray/package/ActionLegacyTrayPluginDelegate.qml
panels/dock/tray/package/tray.qml
panels/dock/tray/traysortordermodel.cpp

style: remove unnecessary local variables

---

debian/changelog

chore: bump version 1.0.2

---

panels/notification-center/CMakeLists.txt
panels/notification-center/notificationcenterpanel.cpp
panels/notification-center/notificationcenterpanel.h
panels/notification-center/notificationcenterproxy.cpp
panels/notification-center/notificationcenterproxy.h
panels/notification-center/package/main.qml

Layout window.
Add Proxy to control window's visible.
Issue: https://pms.uniontech.com/story-view-35587.html

feat: add window's control for notification

---

panels/notification-center/AnimationSettingButton.qml
panels/notification-center/CMakeLists.txt
panels/notification-center/GroupNotify.qml
panels/notification-center/NotifyHeader.qml

add AnimationButton.
Issue: https://pms.uniontech.com/story-view-35587.html

feat: add AnimationButton for notification

---

panels/notification-center/AnimationSettingButton.qml
panels/notification-center/GroupNotify.qml
panels/notification-center/NormalNotify.qml
panels/notification-center/NotifyAction.qml
panels/notification-center/NotifyCenter.qml
panels/notification-center/NotifyHeader.qml
panels/notification-center/SettingActionButton.qml

adjust font and text color.
Issue: Issue: https://pms.uniontech.com/story-view-35587.html

feat: adjust font for notificationcenter

---

panels/notification-center/CMakeLists.txt
panels/notification-center/NormalNotify.qml
panels/notification-center/NotifyItemBackground.qml
panels/notification-center/NotifyItemContent.qml
panels/notification-center/NotifyView.qml
panels/notification-center/OverlapNotify.qml
panels/notification-center/notifymodel.cpp

Add animation when remove notify and overlap.
Issue: https://pms.uniontech.com/story-view-35587.html

feat: add animation for notificationcenter

---

panels/dock/taskmanager/abstractwindow.h
panels/dock/taskmanager/treelandwindow.cpp
panels/dock/taskmanager/treelandwindow.h
panels/dock/taskmanager/x11utils.cpp
panels/dock/taskmanager/x11utils.h
panels/dock/taskmanager/x11window.cpp
panels/dock/taskmanager/x11window.h
panels/dock/taskmanager/x11windowmonitor.cpp

feat: add new winInfo(wmm_class,appid) for window identify

---

panels/dock/taskmanager/CMakeLists.txt
panels/dock/taskmanager/abstractwindow.h
panels/dock/taskmanager/abstractwindowmonitor.cpp
panels/dock/taskmanager/abstractwindowmonitor.h
panels/dock/taskmanager/globals.h
panels/dock/taskmanager/itemmodel.cpp
panels/dock/taskmanager/itemmodel.h
panels/dock/taskmanager/rolecombinemodel.cpp
panels/dock/taskmanager/rolecombinemodel.h
panels/dock/taskmanager/taskmanagersettings.cpp
panels/dock/taskmanager/x11windowmonitor.cpp
panels/dock/taskmanager/x11windowmonitor.h

1. create rolecombinemodel prepare for window and appitems
2. make widnow monitor modelized for 1
log: as title

feat: make window monitor modelized

---

panels/notification-center/NotifyAction.qml
panels/notification-center/NotifyItem.qml
panels/notification-center/NotifyItemBackground.qml
panels/notification-center/NotifyItemContent.qml
panels/notification-center/SettingActionButton.qml

adjust color and size of control.

fix: adjust UI for notificationcenter

---

panels/notification-center/NotifyItem.qml
panels/notification-center/NotifyItemContent.qml
panels/notification-center/NotifyViewDelegate.qml
panels/notification-center/OverlapNotify.qml

chore: support to open link for notificationcenter

---

panels/notification/server/dbusadaptor.cpp
panels/notification/server/dbusadaptor.h
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationmanager.h

feat: export recordCount of notification

---

panels/notification/CMakeLists.txt
panels/notification/bubble/CMakeLists.txt
panels/notification/bubble/package/metadata.json
panels/notification/center/CMakeLists.txt
panels/notification/center/notificationcenterpanel.cpp
panels/notification/center/notifyaccessor.cpp
panels/notification/center/notifyaccessor.h
panels/notification/center/notifyitem.h
panels/notification/center/notifymodel.cpp
panels/notification/center/package/metadata.json
panels/notification/common/dbaccessor.cpp
panels/notification/common/dbaccessor.h
panels/notification/notificationcontainment.cpp
panels/notification/notificationcontainment.h
panels/notification/osd/osdpanel.cpp
panels/notification/osd/package/metadata.json
panels/notification/package/metadata.json
panels/notification/server/CMakeLists.txt
panels/notification/server/notificationmanager.cpp
panels/notification/server/package/metadata.json

Add shared library for NotityEntity for notification plugins.
Add virtual plugin to manage notification plugins.

refact: adjust the structure of notification

---

panels/notification/bubble/bubbleitem.cpp
panels/notification/bubble/bubbleitem.h
panels/notification/bubble/bubblemodel.cpp
panels/notification/bubble/bubblemodel.h
panels/notification/bubble/bubblepanel.cpp
panels/notification/bubble/bubblepanel.h
panels/notification/common/dataaccessor.h
panels/notification/common/dbaccessor.cpp
panels/notification/common/dbaccessor.h
panels/notification/common/notifyentity.cpp
panels/notification/common/notifyentity.h
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationmanager.h
panels/notification/server/notifyserverapplet.cpp
panels/notification/server/notifyserverapplet.h

adjust id and notifyId.
Notification plugin responds based on notification status.
Move expired entity from bubble to server.

refact: unify notification status interaction

---

panels/notification/center/notifyaccessor.cpp
panels/notification/server/configs/org.deepin.dde.shell.notification.json
panels/notification/server/notificationsetting.cpp

chore: complies with the naming conventions of DConfig

---

applets/CMakeLists.txt
applets/dde-apps/CMakeLists.txt
applets/dde-apps/abstractdesktopinfo.h
applets/dde-apps/api/types/am.h
applets/dde-apps/appgroup.cpp
applets/dde-apps/appgroup.h
applets/dde-apps/appgroupmanager.cpp
applets/dde-apps/appgroupmanager.h
applets/dde-apps/appitem.cpp
applets/dde-apps/appitem.h
applets/dde-apps/appitemmodel.cpp
applets/dde-apps/appitemmodel.h
applets/dde-apps/appsapplet.cpp
applets/dde-apps/appsapplet.h
applets/dde-apps/appsdockedhelper.cpp
applets/dde-apps/appsdockedhelper.h
applets/dde-apps/appslaunchtimes.cpp
applets/dde-apps/appslaunchtimes.h
applets/dde-apps/categoryutils.cpp
applets/dde-apps/categoryutils.h
applets/dde-apps/configs/org.deepin.ds.dde-apps.json
applets/dde-apps/desktopinfoam.cpp
applets/dde-apps/desktopinfoam.h
applets/dde-apps/package/metadata.json
debian/dde-shell.install

feat: add new model for all application

---

panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationmanager.h

fix: wrong expired time for notification

---

applets/dde-apps/appitemmodel.cpp

- fix: missing nodisplay for dde-apps

missing nodisplay for dde-apps

---

debian/control

fix: add build-dep for dde-apps

---

panels/notification/center/notifyaccessor.cpp
panels/notification/center/notifyaccessor.h
panels/notification/server/configs/org.deepin.dde.shell.notification.json
panels/notification/server/dbusadaptor.cpp
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationmanager.h
panels/notification/server/notificationsetting.cpp
panels/notification/server/notificationsetting.h

Using dde-apps as app's data source.
Using DConfig as data's store.
Adding cache for app's info.
task: https://pms.uniontech.com/story-view-35587.html

feat: add notification settings

---

.gitignore
CMakeLists.txt

chore: add clang format

---

debian/changelog

chore: bump dev version 1.99.0

---

panels/notification/bubble/bubbleitem.cpp
panels/notification/bubble/bubbleitem.h
panels/notification/center/NotifyHeader.qml
panels/notification/center/notifyaccessor.cpp
panels/notification/center/notifyaccessor.h
panels/notification/common/dbaccessor.cpp
panels/notification/common/notifyentity.cpp
panels/notification/common/notifyentity.h
panels/notification/server/configs/org.deepin.dde.shell.notification.json
panels/notification/server/dbusadaptor.cpp
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationmanager.h
panels/notification/server/notificationsetting.cpp
panels/notification/server/notificationsetting.h
panels/notification/server/notifyserverapplet.cpp
panels/notification/server/notifyserverapplet.h

Add appId for each storaged notification.
default action doesn't have display text.
Add some missing logical for Notify function.
Add configuration for SystemApps.
Optimize the way to obtain insertion IDs.
task: https://pms.uniontech.com/story-view-35587.html

fix: some bug when refacting notification

---

applets/dde-apps/appitemmodel.cpp
applets/dde-apps/appsapplet.cpp
applets/dde-apps/desktopinfoam.cpp
panels/dock/taskmanager/abstractwindow.h
panels/dock/taskmanager/rolecombinemodel.cpp
panels/dock/taskmanager/taskmanager.cpp
panels/dock/taskmanager/taskmanager.h
panels/dock/taskmanager/treelandwindow.cpp
panels/dock/taskmanager/treelandwindow.h
panels/dock/taskmanager/x11window.cpp
panels/dock/taskmanager/x11window.h
tests/panels/dock/taskmanager/CMakeLists.txt
tests/panels/dock/taskmanager/rolecombinemodeltests.cpp

fix: use new model for window identify

---

panels/dock/dockpanel.cpp
panels/notification/bubble/package/main.qml
panels/notification/center/package/main.qml

- fix: missing windowGemoetry changed of dock
- feat: update position of window for notification
task: https://pms.uniontech.com/story-view-35587.html

notification

---

panels/notification/bubble/bubbleitem.cpp
panels/notification/bubble/bubbleitem.h
panels/notification/bubble/package/BubbleContent.qml
panels/notification/center/NotifyItemContent.qml
panels/notification/center/notifyaccessor.cpp
panels/notification/center/notifyitem.cpp
panels/notification/center/notifyitem.h
panels/notification/common/dbaccessor.cpp
panels/notification/common/notifyentity.cpp
panels/notification/common/notifyentity.h
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationsetting.cpp
panels/notification/server/notificationsetting.h

Add a transparent area to receive event.
Support to display image for notification, We only support
image-path currently.
Support to active link.
Add cache for fetch system value.
Optimize log about DBAccessor.
task: https://pms.uniontech.com/story-view-35563.html

feat: support multiple formats notification

---

shell/main.cpp

fix: stuck after the crash

---

frame/pluginloader.cpp
frame/pluginloader.h
panels/dock/taskmanager/taskmanager.cpp

提取 findApplets() 以供非外部项目更方便复用相同逻辑。
Log:

chore: extract findApplets() as a public shell API

---

panels/notification/osd/default/package/main.qml
panels/notification/osd/default/translations/org.deepin.ds.osd.default_es.ts
panels/notification/osd/default/translations/org.deepin.ds.osd.default_pt_BR.ts
panels/notification/osd/default/translations/org.deepin.ds.osd.default_zh_CN.ts
panels/notification/osd/displaymode/displaymodeapplet.cpp
panels/notification/osd/displaymode/displaymodeapplet.h
panels/notification/osd/displaymode/package/main.qml
panels/notification/osd/displaymode/translations/org.deepin.ds.osd.displaymode_es.ts
panels/notification/osd/displaymode/translations/org.deepin.ds.osd.displaymode_pt_BR.ts
panels/notification/osd/displaymode/translations/org.deepin.ds.osd.displaymode_zh_CN.ts
panels/notification/osd/kblayout/package/main.qml
panels/notification/osd/package/main.qml

fix: can't switch displaymode for osd

---

applets/dde-apps/appitem.cpp
applets/dde-apps/appitem.h
applets/dde-apps/appitemmodel.cpp

fix: launctimes is invalid

---

panels/notification/bubble/bubblepanel.cpp
panels/notification/bubble/bubblepanel.h
panels/notification/center/CMakeLists.txt
panels/notification/center/NotifyHeader.qml
panels/notification/center/NotifyStaging.qml
panels/notification/center/notificationcenterpanel.cpp
panels/notification/center/notificationcenterpanel.h
panels/notification/center/notifyaccessor.cpp
panels/notification/center/notifyaccessor.h
panels/notification/center/notifymodel.cpp
panels/notification/center/notifystagingmodel.cpp
panels/notification/center/notifystagingmodel.h
panels/notification/center/package/main.qml
panels/notification/common/dbaccessor.cpp
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationmanager.h

Add staging view to show bubbles when NotificationCenter is shown.
and then NotificationBubble should hide, when NotificationCenter
is hide, it's shown again.

feat: Add staging view for notification

---

panels/notification/bubble/bubbleitem.cpp
panels/notification/bubble/bubblemodel.cpp
panels/notification/bubble/bubblepanel.cpp
panels/notification/center/notificationcenterpanel.cpp
panels/notification/center/notificationcenterproxy.cpp
panels/notification/center/notifyaccessor.cpp
panels/notification/center/notifyitem.cpp
panels/notification/center/notifymodel.cpp
panels/notification/center/notifystagingmodel.cpp
panels/notification/common/dbaccessor.cpp
panels/notification/common/notifyentity.cpp
panels/notification/notificationcontainment.cpp
panels/notification/server/dbusadaptor.cpp
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationsetting.cpp
panels/notification/server/notifyserverapplet.cpp

chore: rename log category for notification

---

panels/dock/CMakeLists.txt
panels/dock/waylanddockhelper.cpp
panels/dock/waylanddockhelper.h

feat: use treeland wallpper color as dock themeType

---

frame/layershell/dlayershellwindow.h
frame/layershell/qwaylandlayershellsurface.cpp
frame/layershell/qwaylandlayershellsurface_p.h
frame/layershell/x11dlayershellemulation.cpp
frame/layershell/x11dlayershellemulation.h

We extend layershell to set window's layer of dde-shell.
task: https://pms.uniontech.com/task-view-365879.html

feat: add LayerOSD to dispaly notification on lock

---

panels/notification/bubble/CMakeLists.txt
panels/notification/bubble/bubblemodel.cpp
panels/notification/bubble/bubblepanel.cpp
panels/notification/bubble/bubblepanel.h
panels/notification/bubble/dbus/xml/org.deepin.dde.SessionManager1.xml
panels/notification/bubble/package/main.qml

feat: support to display on lock for notification

---

.tx/transifex.yaml

chore: update transifex file

---

panels/notification/center/NotifyHeader.qml
panels/notification/center/notifymodel.cpp
panels/notification/center/notifymodel.h

Adjust the logic of displaying discollapse button.

fix: adjust ui for notification

---

debian/changelog
panels/notification/notificationcontainment.cpp

- feat: enable notification plugins
- chore: bump dev version 1.99.1

chore: bump dev version 1.99.1

---

shell/main.cpp

set quickwindow text rendertype to nativetextrendering
log: as title

fix: differ text rendering effect between qml and widget

---

panels/dock/searchitem/translations/org.deepin.ds.dock.searchitem_zh_CN.ts

update translations
Log:
Bug: https://pms.uniontech.com/bug-view-281045.html

fix: update translations

---

frame/layershell/x11dlayershellemulation.cpp

fix: use native resolution in X11 layershell emulation

---

panels/dock/CMakeLists.txt
panels/dock/taskmanager/CMakeLists.txt

chore: rename TreeLand to Treeland

---

panels/dock/DockCompositor.qml
panels/dock/pluginmanagerextension.cpp
panels/dock/pluginmanagerextension_p.h
panels/dock/tray/quickpanel/QuickPanel.qml

Bug: https://pms.uniontech.com/bug-view-272277.html
Log: Receive close quick panel requests from plugins

feat: Receive close quick panel requests from plugins

---

panels/notification/bubble/bubblemodel.cpp
panels/notification/bubble/bubblemodel.h
panels/notification/bubble/bubblepanel.cpp
panels/notification/bubble/bubblepanel.h
panels/notification/server/configs/org.deepin.dde.shell.notification.json
panels/notification/server/notificationmanager.cpp
panels/notification/server/notificationsetting.cpp
panels/notification/server/notificationsetting.h

as title.
Task: https://pms.uniontech.com/task-view-366517.html

feat: add settings for notification

---

debian/changelog

chore: bump dev version 1.99.2

---

frame/layershell/x11dlayershellemulation.cpp

as title.
Task: https://pms.uniontech.com/task-view-366403.html

fix: incorrect position for notification

---

debian/changelog

release 1.99.4
Log: bump version to 1.99.4

chore: bump vesion to 1.99.4

---

panels/dock/taskmanager/treelandwindow.cpp

fix: protocol error caused by surface is nullptr

---

debian/changelog
debian/dcc-dock-plugin.install
panels/dock/dcc-dock-plugin/qml/main.qml

chore: add dcc-dock-plugin install rule

---

panels/dock/taskmanager/taskmanager.cpp

Ignore case when match
log: as title

fix: Some windows cannot be recognized

---

debian/changelog

chore: bump dde-shell to 1.99.6

---

example/bridge-example/package/appletitem.qml

chore: loop binding for example

---

panels/dock/dcc-dock-plugin/qml/PluginArea.qml
panels/dock/dcc-dock-plugin/qml/main.qml
panels/dock/dcc-dock-plugin/translations/dock.ts
panels/dock/dcc-dock-plugin/translations/dock_az.ts
panels/dock/dcc-dock-plugin/translations/dock_bo.ts
panels/dock/dcc-dock-plugin/translations/dock_ca.ts
panels/dock/dcc-dock-plugin/translations/dock_es.ts
panels/dock/dcc-dock-plugin/translations/dock_fi.ts
panels/dock/dcc-dock-plugin/translations/dock_fr.ts
panels/dock/dcc-dock-plugin/translations/dock_hu.ts
panels/dock/dcc-dock-plugin/translations/dock_it.ts
panels/dock/dcc-dock-plugin/translations/dock_ja.ts
panels/dock/dcc-dock-plugin/translations/dock_ko.ts
panels/dock/dcc-dock-plugin/translations/dock_nb_NO.ts
panels/dock/dcc-dock-plugin/translations/dock_pl.ts
panels/dock/dcc-dock-plugin/translations/dock_pt_BR.ts
panels/dock/dcc-dock-plugin/translations/dock_ru.ts
panels/dock/dcc-dock-plugin/translations/dock_uk.ts
panels/dock/dcc-dock-plugin/translations/dock_zh_CN.ts
panels/dock/dcc-dock-plugin/translations/dock_zh_HK.ts
panels/dock/dcc-dock-plugin/translations/dock_zh_TW.ts

As title
Hidden Fashion Mode (Dock has not yet implemented it)
Bug: https://pms.uniontech.com/bug-view-286501.html

fix(dcc-dock-plugin): Interface description text error

---

panels/notification/bubble/bubbleitem.cpp
panels/notification/center/notifyitem.cpp

fix: app crashed when parsing Actions for notification

---

debian/changelog

chore: bump to 1.99.7

---

debian/control

chore: Modify the version that depends on dde-tray-loader-dev

---

panels/dock/dockhelper.cpp

we find transientParent from current to toppest
log: as title

fix: dock will not hide on first launch

---

frame/qml/PanelPopupWindow.qml

fix: avoid popup panel accidentally gets moved

---

panels/notification/server/configs/org.deepin.dde.shell.notification.json

as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-289603.html

fix: Modify 'dndMode' and 'openByTimeInterval' setting default value

---

panels/dock/dcc-dock-plugin/qml/main.qml

Model property assignment error
pms: TASK-286969

fix(dcc-dock-plugin): combobox is empty

---

applets/dde-appearance/appearanceapplet.cpp

Asynchronous calls and cached dbus call results
log: as title

fix: No response caused by DBus

---

debian/changelog

fix: bump to version 1.99.10

---

debian/changelog

chore: bump version 1.99.11

---

panels/dock/searchitem/package/searchitem.qml

fix: searchitem with on menu

---

panels/notification/plugin/NotifyItemContent.qml

fix: critical notification shouldn't close for notification

---

panels/dock/waylanddockhelper.cpp

fix: Avoid crash occurs when reconnecting to treeland

---

debian/changelog

chore: bump version to 1.99.12

---

applets/dde-shutdown/shutdownapplet.cpp
applets/dde-shutdown/shutdownapplet.h

fix: missing default action for shutdown

---

debian/control

chore: update section to shells in debian/control

---

debian/changelog

chore: bump version to 1.99.15

---

panels/notification/plugin/NotifyAction.qml

fix: adjust Action's padding for notification

---

debian/changelog

chore: bump version to 1.99.17

---

debian/changelog

chore: update changelog to UNRELEASED 1.99.19

---

applets/dde-apps/amappitem.cpp
applets/dde-apps/appitem.cpp
applets/dde-apps/appitem.h
applets/dde-apps/appitemmodel.cpp
applets/dde-apps/appitemmodel.h
debian/control

The privacy and security module of dde-control-center
pms: TASK-372065

feat: provide destopFile and isLingLong properties

---

panels/notification/server/notificationmanager.cpp

as title
Log: as title
Bug: PMS-296507

fix: update replace notification entity expired time

---

panels/notification/osd/osdpanel.cpp

delay to showOsd avoid to fetch last value.
pms:TASK-366403

fix: incorrect information for osd

---

panels/notification/common/memoryaccessor.cpp

as title
content may be display error
Log: as title
Pms: BUG-298109

fix: bubble time tip display error

---

panels/notification/server/notificationmanager.cpp

as title
Log: as title
Pms: BUG-299655

fix: bubble do not disappear when it closed from center-stage

---

debian/changelog

chore: bump version to 1.99.21

---

panels/notification/center/notifystagingmodel.cpp

as title
Log: as title
Pms: BUG-303331

fix: Staging notifications cannot disappear after timeout

---

panels/dock/translations/org.deepin.ds.dock.ts
panels/dock/translations/org.deepin.ds.dock_az.ts
panels/dock/translations/org.deepin.ds.dock_bo.ts
panels/dock/translations/org.deepin.ds.dock_ca.ts
panels/dock/translations/org.deepin.ds.dock_es.ts
panels/dock/translations/org.deepin.ds.dock_fi.ts
panels/dock/translations/org.deepin.ds.dock_fr.ts
panels/dock/translations/org.deepin.ds.dock_hu.ts
panels/dock/translations/org.deepin.ds.dock_it.ts
panels/dock/translations/org.deepin.ds.dock_ja.ts
panels/dock/translations/org.deepin.ds.dock_ko.ts
panels/dock/translations/org.deepin.ds.dock_nb_NO.ts
panels/dock/translations/org.deepin.ds.dock_pl.ts
panels/dock/translations/org.deepin.ds.dock_pt_BR.ts
panels/dock/translations/org.deepin.ds.dock_ru.ts
panels/dock/translations/org.deepin.ds.dock_uk.ts
panels/dock/translations/org.deepin.ds.dock_zh_CN.ts
panels/dock/translations/org.deepin.ds.dock_zh_HK.ts
panels/dock/translations/org.deepin.ds.dock_zh_TW.ts

Update translation content
pms: BUG-289221
pms: BUG-286541
pms: BUG-286553

fix: Incorrect application layout menu display content

---

panels/dock/tray/quickpanel/DragItem.qml

添加纵向偏移,避免小图标被鼠标指针图标遮挡
PMS: BUG-293867
Log:

fix: add offset to quick panel drag item to avoid cursor cover icon

---

debian/changelog

chore: bump version to 1.99.24

---

panels/dock/package/main.qml

as title
Log: as title
Pms: BUG-282661

fix: when dock menu is visible, need close other popups

---

panels/dock/taskmanager/package/TaskManager.qml

fix: icon not aligned to center in some cases

---

debian/changelog

chore: bump version to 1.99.25

---

panels/dock/package/main.qml
panels/dock/translations/org.deepin.ds.dock.ts
panels/dock/translations/org.deepin.ds.dock_az.ts
panels/dock/translations/org.deepin.ds.dock_bo.ts
panels/dock/translations/org.deepin.ds.dock_ca.ts
panels/dock/translations/org.deepin.ds.dock_es.ts
panels/dock/translations/org.deepin.ds.dock_fi.ts
panels/dock/translations/org.deepin.ds.dock_fr.ts
panels/dock/translations/org.deepin.ds.dock_hu.ts
panels/dock/translations/org.deepin.ds.dock_it.ts
panels/dock/translations/org.deepin.ds.dock_ja.ts
panels/dock/translations/org.deepin.ds.dock_ko.ts
panels/dock/translations/org.deepin.ds.dock_nb_NO.ts
panels/dock/translations/org.deepin.ds.dock_pl.ts
panels/dock/translations/org.deepin.ds.dock_pt_BR.ts
panels/dock/translations/org.deepin.ds.dock_ru.ts
panels/dock/translations/org.deepin.ds.dock_uk.ts
panels/dock/translations/org.deepin.ds.dock_zh_CN.ts
panels/dock/translations/org.deepin.ds.dock_zh_HK.ts
panels/dock/translations/org.deepin.ds.dock_zh_TW.ts

chore: update translation
